export const env = {
  DATABASE_URL: process.env.DATABASE_URL?.trim() ?? "",
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET?.trim() ?? "",
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL?.trim() ?? "",
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL?.trim() ?? "",
  RESEND_API_KEY: process.env.RESEND_API_KEY?.trim() ?? "",
  EMAIL_FROM: process.env.EMAIL_FROM?.trim() ?? "",
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID ?? "",
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET ?? "",
  PREVIEW_TRUSTED_ORIGINS: process.env.PREVIEW_TRUSTED_ORIGINS ?? "",
  ADMIN_EMAILS: process.env.ADMIN_EMAILS ?? "",
  STORAGE_DRIVER: process.env.STORAGE_DRIVER?.trim() || "local",
  HOSTINGER_STORAGE_ROOT: process.env.HOSTINGER_STORAGE_ROOT?.trim() || "./storage",
  MAX_UPLOAD_SIZE_MB: process.env.MAX_UPLOAD_SIZE_MB ?? "50",
  R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID?.trim() ?? "",
  R2_S3_ENDPOINT: process.env.R2_S3_ENDPOINT?.trim() ?? "",
  R2_BUCKET_PREVIEW: process.env.R2_BUCKET_PREVIEW?.trim() ?? "",
  R2_BUCKET_PROD: process.env.R2_BUCKET_PROD?.trim() ?? "",
  R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID?.trim() ?? "",
  R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY?.trim() ?? "",
} as const;
