import type {
  MethodologyChangeLogEntry,
  MethodologyKnowledgeChunk,
  MethodologyRecordStatus,
  MethodologyRule,
  MethodologyRuleSeverity,
  MethodologyTopic,
  MethodologyUsageSurface,
} from "./types";

const VERSION_ID = "methodology_v2_1";
const BASE_TIME = "2026-06-06T00:00:00.000Z";

const activeRuleSurfaces: MethodologyUsageSurface[] = ["advisor", "scoring", "documentation", "pdf", "rag", "admin"];

function ruleTimestamps() {
  return {
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  };
}

type TopicSeed = Omit<MethodologyTopic, "versionId">;

type RuleSeed = {
  id: string;
  domainId: string;
  topicId: string;
  ruleCode: string;
  title: string;
  severity: MethodologyRuleSeverity;
  evidenceRequired: string[];
  conditionText: string;
  impact: string;
  remediation: string;
  scoringImpact: string;
  confidenceImpact: string;
  automationPotential: string;
  sourceSection: string;
  usageSurface?: MethodologyUsageSurface[];
};

type ChunkSeed = {
  id: string;
  domainId: string;
  topicId: string;
  sourceDocumentId: string;
  chunkKey: string;
  title: string;
  content: string;
  tags: string[];
  intendedUse: MethodologyKnowledgeChunk["intendedUse"];
  relatedRuleCodes: string[];
};

type ChangeLogSeed = Omit<MethodologyChangeLogEntry, "versionId">;

function buildRule(seed: RuleSeed): MethodologyRule {
  return {
    id: seed.id,
    versionId: VERSION_ID,
    domainId: seed.domainId,
    topicId: seed.topicId,
    ruleCode: seed.ruleCode,
    title: seed.title,
    severity: seed.severity,
    evidenceRequired: seed.evidenceRequired,
    conditionText: seed.conditionText,
    impact: seed.impact,
    remediation: seed.remediation,
    scoringImpact: seed.scoringImpact,
    confidenceImpact: seed.confidenceImpact,
    automationPotential: seed.automationPotential,
    sourceSection: seed.sourceSection,
    status: "active" as MethodologyRecordStatus,
    usageSurface: seed.usageSurface ?? [...activeRuleSurfaces],
    ...ruleTimestamps(),
  };
}

function buildChunk(seed: ChunkSeed): MethodologyKnowledgeChunk {
  return {
    id: seed.id,
    versionId: VERSION_ID,
    domainId: seed.domainId,
    topicId: seed.topicId,
    sourceDocumentId: seed.sourceDocumentId,
    chunkKey: seed.chunkKey,
    title: seed.title,
    content: seed.content,
    tags: seed.tags,
    intendedUse: seed.intendedUse,
    embeddingStatus: "indexed",
    status: "active" as MethodologyRecordStatus,
    relatedRuleCodes: seed.relatedRuleCodes,
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  };
}

const METHODOLOGY_EXPANDED_TOPIC_SEEDS: TopicSeed[] = [
  { id: "topic-governance-trace", domainId: "domain-governance-scoring", key: "rule-trace", title: "Rule trace", summary: "Tracing, overrides and technical debt decisions.", order: 14 },
  { id: "topic-governance-gates", domainId: "domain-governance-scoring", key: "gates", title: "Gates y overrides", summary: "G0-G5 gates and auditable override handling.", order: 15 },
  { id: "topic-governance-claims", domainId: "domain-governance-scoring", key: "claims-safety", title: "Claim safety", summary: "Unsafe wording, safe alternatives and bounded language.", order: 16 },
  { id: "topic-vmware-cpu", domainId: "domain-vmware", key: "vmware-cpu", title: "CPU y sizing", summary: "vCPU allocation, oversubscription and host headroom.", order: 17 },
  { id: "topic-vmware-network", domainId: "domain-vmware", key: "vmware-network", title: "Network y vHealth", summary: "NIC mapping, vHealth and maintenance windows.", order: 18 },
  { id: "topic-proxmox-kvm", domainId: "domain-proxmox", key: "proxmox-kvm", title: "KVM y LXC", summary: "VM and container readiness for the target.", order: 19 },
  { id: "topic-proxmox-backup", domainId: "domain-proxmox", key: "proxmox-backup", title: "PBS y backup", summary: "Backup target, restore proof and retention.", order: 20 },
  { id: "topic-san-resilience", domainId: "domain-san-storage", key: "san-resilience", title: "Resiliencia SAN", summary: "Array health, cache protection and replication.", order: 21 },
  { id: "topic-san-capacity", domainId: "domain-san-storage", key: "san-capacity", title: "Capacidad SAN", summary: "Capacity runway and degradation detection.", order: 22 },
  { id: "topic-network-transport", domainId: "domain-networking", key: "network-transport", title: "Transporte de red", summary: "LACP, MLAG and migration network capacity.", order: 23 },
  { id: "topic-network-overlay", domainId: "domain-networking", key: "network-overlay", title: "Overlay y SDN", summary: "Overlay, NAT and routing for segmented moves.", order: 24 },
  { id: "topic-app-stateful", domainId: "domain-applications", key: "app-stateful", title: "Stateful apps", summary: "Shared services, IPs and SLA dependencies.", order: 25 },
  { id: "topic-app-licensing", domainId: "domain-applications", key: "app-licensing", title: "Licensing", summary: "License checks tied to CPU or host identity.", order: 26 },
  { id: "topic-target-compute", domainId: "domain-target-readiness", key: "target-compute", title: "Compute del target", summary: "CPU, RAM and performance headroom.", order: 27 },
  { id: "topic-target-validation", domainId: "domain-target-readiness", key: "target-validation", title: "Validacion del target", summary: "Synthetic workload, backup target and HA/DR parity.", order: 28 },
  { id: "topic-security-access", domainId: "domain-security", key: "security-access", title: "Acceso y secretos", summary: "Access separation and secret hygiene.", order: 29 },
  { id: "topic-security-backup", domainId: "domain-security", key: "security-backup", title: "Backup y DR security", summary: "Immutable backup and recovery boundaries.", order: 30 },
  { id: "topic-execution-smoke", domainId: "domain-execution", key: "execution-smoke", title: "Smoke y performance", summary: "Cutover smoke tests and degradation checks.", order: 31 },
  { id: "topic-execution-hypercare", domainId: "domain-execution", key: "execution-hypercare", title: "Hypercare", summary: "Closure criteria and post-cutover owners.", order: 32 },
  { id: "topic-remediation-queue", domainId: "domain-remediation", key: "remediation-queue", title: "Queue de remediacion", summary: "Accepted debt and remediation owners.", order: 33 },
  { id: "topic-remediation-debt", domainId: "domain-remediation", key: "remediation-debt", title: "Deuda tecnica aceptada", summary: "Debt acceptance and expiry boundaries.", order: 34 },
  { id: "topic-checklists-governance", domainId: "domain-checklists", key: "checklists-governance", title: "Checklists de gate", summary: "Gate checklists and decision hygiene.", order: 35 },
  { id: "topic-checklists-postcutover", domainId: "domain-checklists", key: "checklists-postcutover", title: "Post-cutover", summary: "Post-cutover checks and handoff closure.", order: 36 },
];

export const METHODOLOGY_EXPANDED_TOPICS: MethodologyTopic[] = METHODOLOGY_EXPANDED_TOPIC_SEEDS.map((topic) => ({
  ...topic,
  versionId: VERSION_ID,
}));

export const METHODOLOGY_EXPANDED_RULES: MethodologyRule[] = [
  // Governance / scoring / claims
  buildRule({
    id: "rule-gov-trace-002",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-trace",
    ruleCode: "SE-GOV-TRC-002",
    title: "Trace y override deben quedar auditados",
    severity: "high",
    evidenceRequired: ["rule trace", "override log", "owner", "timestamp"],
    conditionText: "Sin trazabilidad de regla, override y motivo no hay cierre metodologico.",
    impact: "Se pierde auditabilidad y aumenta el riesgo de decisiones no explicadas.",
    remediation: "Registrar la regla aplicada, quien overrideo y por que.",
    scoringImpact: "Penaliza cualquier override sin evidencia de decision.",
    confidenceImpact: "Confidence se mantiene conservadora hasta ver audit trail.",
    automationPotential: "Medium: los logs pueden derivar la evidencia de override.",
    sourceSection: "v2.1 / governance / trace",
  }),
  buildRule({
    id: "rule-gov-gates-002",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-gates",
    ruleCode: "SE-GOV-GAT-002",
    title: "Gates G0-G5 requieren decision log",
    severity: "blocking",
    evidenceRequired: ["gate log", "owner", "timestamp", "decision reason"],
    conditionText: "Cada gate debe existir con owner y decision log antes de avanzar.",
    impact: "Evita pasar por alto un gate incompleto o informal.",
    remediation: "Publicar el gate con responsable, timestamp y resultado.",
    scoringImpact: "Go/no-go remains blocked until gate completion is explicit.",
    confidenceImpact: "Confidence cannot be high while gates are unresolved.",
    automationPotential: "High: the checklist can map gate completion deterministically.",
    sourceSection: "v2.1 / governance / gates",
  }),
  buildRule({
    id: "rule-gov-contradiction-001",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-claims",
    ruleCode: "SE-GOV-CTR-001",
    title: "Evidencia contradictoria baja la confidence",
    severity: "critical",
    evidenceRequired: ["conflict log", "source timestamps", "owner review"],
    conditionText: "Si dos evidencias se contradicen, la decision debe seguir conservadora.",
    impact: "Evita narrativas optimistas sobre datasets incompatibles.",
    remediation: "Resolver el conflicto antes de publicar una conclusion.",
    scoringImpact: "Readiness is capped until the contradiction is resolved.",
    confidenceImpact: "Confidence must drop when the evidence set conflicts.",
    automationPotential: "Medium: contradictions can be flagged from source timestamps.",
    sourceSection: "v2.1 / governance / contradictions",
  }),
  buildRule({
    id: "rule-gov-ovr-001",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-trace",
    ruleCode: "SE-GOV-OVR-001",
    title: "Overrides auditables y con fecha de expiracion",
    severity: "high",
    evidenceRequired: ["override reason", "owner", "expiry", "audit log"],
    conditionText: "Un override sin vigencia ni owner no debe usarse como estado final.",
    impact: "Limita el abuso de excepciones temporales.",
    remediation: "Registrar expiracion y owner del override.",
    scoringImpact: "Temporary override does not lift the readiness cap by itself.",
    confidenceImpact: "Confidence remains constrained until the override expires or closes.",
    automationPotential: "Medium: admin actions can seed the override log.",
    sourceSection: "v2.1 / governance / overrides",
  }),
  buildRule({
    id: "rule-gov-debt-001",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-gates",
    ruleCode: "SE-GOV-DTB-001",
    title: "Deuda tecnica aceptada debe quedar limitada",
    severity: "medium",
    evidenceRequired: ["debt note", "owner", "expiry", "risk acceptance"],
    conditionText: "La deuda aceptada no puede confundirse con un cierre real de gap.",
    impact: "Evita que el proyecto actue como si el riesgo ya no existiera.",
    remediation: "Marcar alcance, owner y fecha de reevaluacion.",
    scoringImpact: "Debt acceptance reduces but does not remove the penalty.",
    confidenceImpact: "Confidence may improve, but not to full closure.",
    automationPotential: "Low: requires human sign-off and expiry tracking.",
    sourceSection: "v2.1 / governance / debt",
  }),
  buildRule({
    id: "rule-gov-safe-claim-001",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-claims",
    ruleCode: "SE-GOV-SCL-001",
    title: "Claims seguros deben citar evidencia y limites",
    severity: "critical",
    evidenceRequired: ["evidence references", "blocker summary", "safe wording"],
    conditionText: "No se deben publicar claims absolutos si la evidencia sigue siendo parcial.",
    impact: "Reduce el riesgo comercial y operativo de sobrepromesas.",
    remediation: "Reescribir con limites, gaps y siguiente paso concreto.",
    scoringImpact: "Claim safety applies before any readiness claim is shown.",
    confidenceImpact: "Confidence language must remain bounded by evidence.",
    automationPotential: "High: wording can be linted against the claim validator.",
    sourceSection: "v2.1 / governance / claim safety",
  }),

  // VMware
  buildRule({
    id: "rule-vmw-cpu-001",
    domainId: "domain-vmware",
    topicId: "topic-vmware-cpu",
    ruleCode: "SE-VMW-CPU-001",
    title: "CPU VMware requiere baseline y oversubscription",
    severity: "high",
    evidenceRequired: ["cpu baseline", "peak trend", "oversubscription", "host headroom"],
    conditionText: "Sin baseline de CPU no se puede estimar la migracion sin riesgo.",
    impact: "CPU contention puede esconderse hasta el momento de corte.",
    remediation: "Medir peak y headroom antes de cerrar el sizing.",
    scoringImpact: "Readiness penalized when CPU is not baselined.",
    confidenceImpact: "Confidence remains medium until host headroom is known.",
    automationPotential: "High: CPU metrics can feed the KB deterministically.",
    sourceSection: "v2.1 / VMware / cpu",
  }),
  buildRule({
    id: "rule-vmw-host-001",
    domainId: "domain-vmware",
    topicId: "topic-vmware-cpu",
    ruleCode: "SE-VMW-HST-001",
    title: "ESXi hosts y maintenance mode deben estar claros",
    severity: "medium",
    evidenceRequired: ["host inventory", "maintenance plan", "placement policy", "capacity"],
    conditionText: "Un host sin plan de maintenance o sin placement policy complica el corte.",
    impact: "Puede generar reubicacion inesperada y ventanas mas largas.",
    remediation: "Validar inventario de hosts y ventanas de mantenimiento.",
    scoringImpact: "Moderate penalty until host maintenance is planned.",
    confidenceImpact: "Confidence drops if host inventory is stale.",
    automationPotential: "Medium: host inventories are easy to normalize.",
    sourceSection: "v2.1 / VMware / hosts",
  }),
  buildRule({
    id: "rule-vmw-net-001",
    domainId: "domain-vmware",
    topicId: "topic-vmware-network",
    ruleCode: "SE-VMW-NET-001",
    title: "NICs, portgroups y vSwitch deben validarse",
    severity: "high",
    evidenceRequired: ["nic mapping", "portgroup map", "vSwitch config", "MTU"],
    conditionText: "La red VMware debe estar mapeada antes de asumir compatibilidad con el target.",
    impact: "Evita errores de conectividad y caidas de servicios post-migracion.",
    remediation: "Comparar mapeo de NICs, vSwitches y portgroups con el target.",
    scoringImpact: "Network readiness capped until mapping is explicit.",
    confidenceImpact: "Confidence remains bounded by the least clear network path.",
    automationPotential: "High: network mappings are structured and machine-readable.",
    sourceSection: "v2.1 / VMware / network",
  }),
  buildRule({
    id: "rule-vmw-vhealth-001",
    domainId: "domain-vmware",
    topicId: "topic-vmware-network",
    ruleCode: "SE-VMW-VHL-001",
    title: "vHealth y warnings operativos no se ignoran",
    severity: "medium",
    evidenceRequired: ["vHealth export", "warning summary", "owner review"],
    conditionText: "Los warnings de salud deben leerse como señales de riesgo, no como ruido.",
    impact: "Ayuda a evitar migrar sobre hosts con alertas silenciosas.",
    remediation: "Revisar y clasificar cada warning antes del go/no-go.",
    scoringImpact: "Health warnings lower readiness until reviewed.",
    confidenceImpact: "Confidence cannot be high with unreviewed warnings.",
    automationPotential: "Medium: health summaries can seed the KB.",
    sourceSection: "v2.1 / VMware / vHealth",
  }),
  buildRule({
    id: "rule-vmw-lic-001",
    domainId: "domain-vmware",
    topicId: "topic-vmware-network",
    ruleCode: "SE-VMW-LIC-001",
    title: "Licensing VMware debe quedar trazado",
    severity: "critical",
    evidenceRequired: ["license inventory", "expiry", "migration rights", "owner"],
    conditionText: "Sin licencia y derechos claros la migracion puede fallar por compliance.",
    impact: "Evita sorpresas legales o tecnicas al mover workloads.",
    remediation: "Validar licencias, expiracion y derechos de movimiento.",
    scoringImpact: "Hard block while licensing is unresolved.",
    confidenceImpact: "Confidence stays low until license coverage is explicit.",
    automationPotential: "Medium: license inventories can be imported deterministically.",
    sourceSection: "v2.1 / VMware / licensing",
  }),
  buildRule({
    id: "rule-vmw-snp-002",
    domainId: "domain-vmware",
    topicId: "topic-vmware-cpu",
    ruleCode: "SE-VMW-SNP-002",
    title: "Snapshots deben tener ventana de limpieza",
    severity: "medium",
    evidenceRequired: ["snapshot age", "owner", "cleanup plan"],
    conditionText: "Snapshots sin ventana de limpieza deben tratarse como riesgo operativo.",
    impact: "Reduce performance y complica rollback.",
    remediation: "Asignar owner y ventana de limpieza.",
    scoringImpact: "Readiness penalized until snapshots are cleared or justified.",
    confidenceImpact: "Confidence lowers when snapshot hygiene is poor.",
    automationPotential: "High: snapshot age can be extracted from exports.",
    sourceSection: "v2.1 / VMware / snapshots",
  }),
  buildRule({
    id: "rule-vmw-bkp-002",
    domainId: "domain-vmware",
    topicId: "topic-vmware-network",
    ruleCode: "SE-VMW-BKP-002",
    title: "Backup VMware requiere retencion y scope visible",
    severity: "high",
    evidenceRequired: ["retention", "scope", "job status", "owner"],
    conditionText: "Un backup sin scope y retencion claras no puede dar confianza completa.",
    impact: "Evita asumir cobertura que no existe para workloads criticos.",
    remediation: "Publicar scope, retencion y owner del backup.",
    scoringImpact: "Readiness capped until backup scope is explicit.",
    confidenceImpact: "Confidence remains medium while backup scope is partial.",
    automationPotential: "High: job histories and retention policies are structured.",
    sourceSection: "v2.1 / VMware / backup scope",
  }),

  // Proxmox
  buildRule({
    id: "rule-pve-kvm-001",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-kvm",
    ruleCode: "SE-PVE-KVM-001",
    title: "KVM/QEMU baseline del target",
    severity: "high",
    evidenceRequired: ["kvm features", "qemu version", "cpu flags", "compatibility"],
    conditionText: "No se puede asumir compatibilidad si KVM/QEMU no esta alineado.",
    impact: "Evita fallos de arranque o features perdidas en el target.",
    remediation: "Validar version y flags antes del corte.",
    scoringImpact: "Target readiness penalized until hypervisor baseline matches.",
    confidenceImpact: "Confidence remains medium without compatibility proof.",
    automationPotential: "Medium: versions and flags can be normalized from inventory.",
    sourceSection: "v2.1 / Proxmox VE / kvm",
  }),
  buildRule({
    id: "rule-pve-lxc-001",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-kvm",
    ruleCode: "SE-PVE-LXC-001",
    title: "Contenedores LXC requieren reglas separadas",
    severity: "medium",
    evidenceRequired: ["lxc inventory", "privilege mode", "storage mapping", "network map"],
    conditionText: "LXC no debe tratarse igual que una VM sin revisar privilegios y storage.",
    impact: "Evita mover contenedores con assumptions equivocadas.",
    remediation: "Catalogar LXC y validar su perfil por separado.",
    scoringImpact: "Separate readiness lane for containers.",
    confidenceImpact: "Confidence bounded by container-specific evidence.",
    automationPotential: "High: container inventory is structured enough for the KB.",
    sourceSection: "v2.1 / Proxmox VE / lxc",
  }),
  buildRule({
    id: "rule-pve-ceph-001",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-backup",
    ruleCode: "SE-PVE-CEP-001",
    title: "Ceph y storage compartido deben estar sanos",
    severity: "critical",
    evidenceRequired: ["ceph health", "osd status", "pg state", "latency"],
    conditionText: "Sin salud de Ceph el target no debe declararse listo.",
    impact: "Ceph degradado puede afectar toda la ventana de migracion.",
    remediation: "Validar health, OSDs y latencia antes del go/no-go.",
    scoringImpact: "Hard block until storage health is green.",
    confidenceImpact: "Confidence remains low with any Ceph health issue.",
    automationPotential: "Medium: Ceph health can be ingested from exports.",
    sourceSection: "v2.1 / Proxmox VE / ceph",
  }),
  buildRule({
    id: "rule-pve-net-001",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-kvm",
    ruleCode: "SE-PVE-NET-001",
    title: "Network target Proxmox debe coincidir con el plan",
    severity: "high",
    evidenceRequired: ["bridge map", "vlan map", "mtu", "routing"],
    conditionText: "Las bridges y VLANs del target deben validarse antes del corte.",
    impact: "Reduce el riesgo de mover workloads a una red incompleta.",
    remediation: "Comparar el plan de red con el mapping real.",
    scoringImpact: "Target readiness capped until network alignment is explicit.",
    confidenceImpact: "Confidence remains medium without target network proof.",
    automationPotential: "High: bridge and VLAN configs are parseable artifacts.",
    sourceSection: "v2.1 / Proxmox VE / network",
  }),
  buildRule({
    id: "rule-pve-pbs-001",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-backup",
    ruleCode: "SE-PVE-PBS-001",
    title: "PBS y backup target requieren restore proof",
    severity: "critical",
    evidenceRequired: ["pbs job status", "restore proof", "retention", "owner"],
    conditionText: "PBS sin restore proof no debe usarse como cierre de backup.",
    impact: "Sin restore no hay evidencia real de recuperacion.",
    remediation: "Ejecutar restore test y documentar resultado.",
    scoringImpact: "Hard block until backup restore evidence exists.",
    confidenceImpact: "Confidence stays low until restore proof is available.",
    automationPotential: "Medium: PBS job outputs and restore artifacts can be cataloged.",
    sourceSection: "v2.1 / Proxmox VE / pbs",
  }),

  // SAN / storage
  buildRule({
    id: "rule-san-mpath-001",
    domainId: "domain-san-storage",
    topicId: "topic-san-resilience",
    ruleCode: "SE-SAN-MPT-001",
    title: "Multipath y paths activos deben verificarse",
    severity: "critical",
    evidenceRequired: ["active paths", "failover test", "latency", "zoning"],
    conditionText: "Sin multipath sano el storage queda expuesto a degradacion o corte.",
    impact: "Puede provocar IO loss o path flapping durante la migracion.",
    remediation: "Validar paths y failover antes de avanzar.",
    scoringImpact: "Storage readiness blocked until multipath is green.",
    confidenceImpact: "Confidence remains low with path instability.",
    automationPotential: "Medium: switch and host outputs can seed the KB.",
    sourceSection: "v2.1 / SAN / multipath",
  }),
  buildRule({
    id: "rule-san-cap-001",
    domainId: "domain-san-storage",
    topicId: "topic-san-capacity",
    ruleCode: "SE-SAN-CAP-001",
    title: "Capacidad SAN con runway y crecimiento",
    severity: "high",
    evidenceRequired: ["capacity runway", "growth trend", "reserved space", "forecast"],
    conditionText: "Una SAN con capacidad nominal pero sin runway no es safe enough.",
    impact: "Evita sobrecargar arrays justo despues del corte.",
    remediation: "Recalcular capacidad util y margen de crecimiento.",
    scoringImpact: "Readiness penalized until runway is explicit.",
    confidenceImpact: "Confidence cannot be high without growth forecast.",
    automationPotential: "High: capacity telemetry is structured and repeatable.",
    sourceSection: "v2.1 / SAN / capacity",
  }),
  buildRule({
    id: "rule-san-cache-001",
    domainId: "domain-san-storage",
    topicId: "topic-san-resilience",
    ruleCode: "SE-SAN-CAC-001",
    title: "Write cache protection y battery health",
    severity: "critical",
    evidenceRequired: ["cache protection", "battery health", "controller status"],
    conditionText: "Sin cache protection o bateria sana el storage no esta listo.",
    impact: "Evita perdida de datos o performance erratica por cache insegura.",
    remediation: "Verificar bateria, cache y controlador antes del go/no-go.",
    scoringImpact: "Hard block while cache protection is unresolved.",
    confidenceImpact: "Confidence remains low until cache health is explicit.",
    automationPotential: "Medium: controller health can be harvested from tools.",
    sourceSection: "v2.1 / SAN / cache",
  }),
  buildRule({
    id: "rule-san-repl-001",
    domainId: "domain-san-storage",
    topicId: "topic-san-resilience",
    ruleCode: "SE-SAN-REP-001",
    title: "Replication y DR requieren sincronizacion",
    severity: "high",
    evidenceRequired: ["replication lag", "dr plan", "recovery point", "owner"],
    conditionText: "La replication asincrona sin lag reportado no es evidencia suficiente.",
    impact: "Puede ocultar desfasaje o perdida de datos en DR.",
    remediation: "Validar lag, objetivo de recuperacion y owner de DR.",
    scoringImpact: "Penalize readiness until DR parity is visible.",
    confidenceImpact: "Confidence bounded by replication lag and DR proof.",
    automationPotential: "Medium: replication stats can be parsed from the platform.",
    sourceSection: "v2.1 / SAN / replication",
  }),

  // Networking
  buildRule({
    id: "rule-net-lacp-001",
    domainId: "domain-networking",
    topicId: "topic-network-transport",
    ruleCode: "SE-NET-LAC-001",
    title: "LACP y MLAG deben quedar validados",
    severity: "high",
    evidenceRequired: ["bonding", "lacp status", "mlag status", "failover"],
    conditionText: "Una agregacion de links sin validacion de failover no es suficiente.",
    impact: "Puede producir corte parcial o perdida de throughput.",
    remediation: "Validar bonding, LACP y MLAG antes del cutover.",
    scoringImpact: "Network readiness capped until link aggregation is proven.",
    confidenceImpact: "Confidence remains medium while failover is unproven.",
    automationPotential: "High: network configs can be parsed and checked.",
    sourceSection: "v2.1 / networking / transport",
  }),
  buildRule({
    id: "rule-net-mtu-001",
    domainId: "domain-networking",
    topicId: "topic-network-transport",
    ruleCode: "SE-NET-MTU-001",
    title: "MTU y jumbo frames consistentes",
    severity: "critical",
    evidenceRequired: ["mtu map", "jumbo validation", "routing path"],
    conditionText: "Inconsistencias de MTU pueden romper performance o conectividad.",
    impact: "Evita fragmentation y fallas silenciosas post-migracion.",
    remediation: "Alinear MTU en toda la ruta antes de avanzar.",
    scoringImpact: "Hard block until MTU is consistent end to end.",
    confidenceImpact: "Confidence remains low when MTU is inconsistent.",
    automationPotential: "High: MTU values are easy to compare across hops.",
    sourceSection: "v2.1 / networking / mtu",
  }),
  buildRule({
    id: "rule-net-rout-001",
    domainId: "domain-networking",
    topicId: "topic-network-overlay",
    ruleCode: "SE-NET-ROU-001",
    title: "Routing y NAT deben estar documentados",
    severity: "high",
    evidenceRequired: ["routing table", "nat policy", "exceptions", "owner"],
    conditionText: "No asumir conectividad si routing o NAT no estan documentados.",
    impact: "Evita perder accesos a apps y servicios compartidos.",
    remediation: "Documentar rutas y NAT antes del cutover.",
    scoringImpact: "Readiness reduced until routing is clear.",
    confidenceImpact: "Confidence remains bounded by routing ambiguity.",
    automationPotential: "Medium: routing exports can be ingested.",
    sourceSection: "v2.1 / networking / routing",
  }),
  buildRule({
    id: "rule-net-ovl-001",
    domainId: "domain-networking",
    topicId: "topic-network-overlay",
    ruleCode: "SE-NET-OVL-001",
    title: "Overlay / SDN y segmentos virtuales",
    severity: "medium",
    evidenceRequired: ["overlay map", "sdn policy", "segment owner"],
    conditionText: "Las redes overlay deben explicitar su mapeo con el target.",
    impact: "Evita quedarte con segmentacion incompleta o invisibilidad.",
    remediation: "Mapear overlay, segment owner y policy.",
    scoringImpact: "Moderate penalty until overlay mapping is visible.",
    confidenceImpact: "Confidence remains medium with overlay ambiguity.",
    automationPotential: "Medium: SDN policies can be cataloged.",
    sourceSection: "v2.1 / networking / overlay",
  }),
  buildRule({
    id: "rule-net-cap-001",
    domainId: "domain-networking",
    topicId: "topic-network-transport",
    ruleCode: "SE-NET-CAP-001",
    title: "Capacidad de red para la ventana de migracion",
    severity: "high",
    evidenceRequired: ["bandwidth", "peak window", "contention", "migration lane"],
    conditionText: "Sin capacidad de red para la ventana, el plan queda subdimensionado.",
    impact: "Puede extender la ventana y afectar SLAs.",
    remediation: "Medir peak window y reservar migration lane.",
    scoringImpact: "Network readiness limited by contention.",
    confidenceImpact: "Confidence cannot be high without bandwidth proof.",
    automationPotential: "High: throughput metrics can feed the KB.",
    sourceSection: "v2.1 / networking / capacity",
  }),

  // Applications
  buildRule({
    id: "rule-app-stateful-001",
    domainId: "domain-applications",
    topicId: "topic-app-stateful",
    ruleCode: "SE-APP-STA-001",
    title: "Stateful apps requieren plan por sistema",
    severity: "critical",
    evidenceRequired: ["app owner", "state dependencies", "maintenance window"],
    conditionText: "Una app stateful sin plan individual no debe moverse por default.",
    impact: "Evita romper state, colas o persistencia de negocio.",
    remediation: "Definir plan individual para cada app stateful.",
    scoringImpact: "Hard block until app state is mapped.",
    confidenceImpact: "Confidence remains low while app state is opaque.",
    automationPotential: "Medium: app inventories can be normalized.",
    sourceSection: "v2.1 / applications / stateful",
  }),
  buildRule({
    id: "rule-app-license-001",
    domainId: "domain-applications",
    topicId: "topic-app-licensing",
    ruleCode: "SE-APP-LIC-001",
    title: "Licensing ligado a hardware o CPU",
    severity: "critical",
    evidenceRequired: ["license terms", "cpu binding", "owner", "expiry"],
    conditionText: "Las licencias atadas a host o CPU deben revisarse antes del corte.",
    impact: "Evita violar compliance o dejar servicios inutilizados.",
    remediation: "Revisar terminos y revalidar licencias post-migracion.",
    scoringImpact: "Blocks readiness until licensing is explicit.",
    confidenceImpact: "Confidence remains low while licensing is unresolved.",
    automationPotential: "Medium: licensing data can be cataloged from docs.",
    sourceSection: "v2.1 / applications / licensing",
  }),
  buildRule({
    id: "rule-app-shared-001",
    domainId: "domain-applications",
    topicId: "topic-app-stateful",
    ruleCode: "SE-APP-SHR-001",
    title: "Shared services y dependencias comunes",
    severity: "high",
    evidenceRequired: ["shared service map", "consumer list", "owner", "change window"],
    conditionText: "Un shared service sin mapa de consumidores introduce riesgo amplio.",
    impact: "Puede afectar multiples workloads si el plan no es secuenciado.",
    remediation: "Mapear consumidores y secuencia de migracion.",
    scoringImpact: "Readiness capped until shared services are explicit.",
    confidenceImpact: "Confidence remains medium when shared services are uncertain.",
    automationPotential: "Medium: dependency maps can be normalized.",
    sourceSection: "v2.1 / applications / shared services",
  }),
  buildRule({
    id: "rule-app-fixip-001",
    domainId: "domain-applications",
    topicId: "topic-app-stateful",
    ruleCode: "SE-APP-FIP-001",
    title: "Integraciones con IP fija deben ser visibles",
    severity: "high",
    evidenceRequired: ["fixed ip list", "integration owners", "routing exception"],
    conditionText: "Las integraciones con IP fija deben revalidarse en el target.",
    impact: "Evita cortar integraciones silenciosas.",
    remediation: "Listar IP fija, owner y ruta de validacion.",
    scoringImpact: "Readiness reduced until fixed IP dependencies are mapped.",
    confidenceImpact: "Confidence remains medium with unresolved integrations.",
    automationPotential: "Medium: configs and integration lists can seed the KB.",
    sourceSection: "v2.1 / applications / fixed IP",
  }),
  buildRule({
    id: "rule-app-sla-001",
    domainId: "domain-applications",
    topicId: "topic-app-stateful",
    ruleCode: "SE-APP-SLA-001",
    title: "Tier 1 SLA dependencies need owner sign-off",
    severity: "critical",
    evidenceRequired: ["sla tier", "owner sign-off", "window", "rollback impact"],
    conditionText: "Una dependencia Tier 1 sin owner no puede quedar marcada como segura.",
    impact: "Protege servicios criticos de una migracion no coordinada.",
    remediation: "Obtener sign-off y ventana para cada dependencia Tier 1.",
    scoringImpact: "Hard block while Tier 1 owners have not signed off.",
    confidenceImpact: "Confidence cannot be high until critical SLAs are approved.",
    automationPotential: "Medium: service maps and owner lists can be normalized.",
    sourceSection: "v2.1 / applications / sla",
  }),

  // Target readiness
  buildRule({
    id: "rule-tgt-compute-001",
    domainId: "domain-target-readiness",
    topicId: "topic-target-compute",
    ruleCode: "SE-TGT-CMP-001",
    title: "CPU y RAM del target con headroom suficiente",
    severity: "critical",
    evidenceRequired: ["cpu headroom", "ram headroom", "growth forecast"],
    conditionText: "Sin headroom la plataforma target no puede considerarse segura.",
    impact: "Evita saturacion inmediata tras el cutover.",
    remediation: "Recalcular sizing con forecast real.",
    scoringImpact: "Hard block while compute headroom is insufficient.",
    confidenceImpact: "Confidence remains low until target capacity is explicit.",
    automationPotential: "High: compute metrics are ideal for deterministic seeding.",
    sourceSection: "v2.1 / target / compute",
  }),
  buildRule({
    id: "rule-tgt-storage-001",
    domainId: "domain-target-readiness",
    topicId: "topic-target-validation",
    ruleCode: "SE-TGT-STR-001",
    title: "Storage target debe mostrar performance y capacidad",
    severity: "high",
    evidenceRequired: ["storage perf", "capacity runway", "tier map"],
    conditionText: "Storage target sin performance ni runway no es suficiente.",
    impact: "Puede introducir cuello de botella o espacio insuficiente.",
    remediation: "Medir rendimiento y runway antes del go/no-go.",
    scoringImpact: "Readiness capped until storage proof is available.",
    confidenceImpact: "Confidence remains medium without storage validation.",
    automationPotential: "High: storage telemetry is structured and reusable.",
    sourceSection: "v2.1 / target / storage",
  }),
  buildRule({
    id: "rule-tgt-net-001",
    domainId: "domain-target-readiness",
    topicId: "topic-target-validation",
    ruleCode: "SE-TGT-NET-001",
    title: "Segmentos de red target alineados",
    severity: "high",
    evidenceRequired: ["target segments", "routing map", "vlan proof"],
    conditionText: "No se puede declarar target listo si segmentos o rutas no coinciden.",
    impact: "Evita mover workloads a una red parcialmente construida.",
    remediation: "Comparar segmentos y rutas con la arquitectura objetivo.",
    scoringImpact: "Target readiness capped until segments are aligned.",
    confidenceImpact: "Confidence remains medium without target network proof.",
    automationPotential: "High: segment maps are structured and deterministic.",
    sourceSection: "v2.1 / target / network",
  }),
  buildRule({
    id: "rule-tgt-backup-001",
    domainId: "domain-target-readiness",
    topicId: "topic-target-validation",
    ruleCode: "SE-TGT-BKP-001",
    title: "Backup target y restore proof del destino",
    severity: "critical",
    evidenceRequired: ["backup target", "restore proof", "owner"],
    conditionText: "No declarar ready un target sin backup y restore proof visibles.",
    impact: "Evita quedar sin recuperacion en el destino.",
    remediation: "Validar backup target y restore proof antes del corte.",
    scoringImpact: "Hard block until target backup proof exists.",
    confidenceImpact: "Confidence remains low while backup target is unclear.",
    automationPotential: "Medium: backup target data can be ingested from jobs.",
    sourceSection: "v2.1 / target / backup",
  }),
  buildRule({
    id: "rule-tgt-hadr-001",
    domainId: "domain-target-readiness",
    topicId: "topic-target-validation",
    ruleCode: "SE-TGT-HDR-001",
    title: "HA/DR parity entre source y target",
    severity: "high",
    evidenceRequired: ["ha parity", "dr parity", "recovery plan"],
    conditionText: "Si HA o DR quedan por debajo del source, la confianza baja.",
    impact: "Evita suponer continuidad que aun no existe.",
    remediation: "Comparar HA y DR contra la plataforma origen.",
    scoringImpact: "Readiness reduced until HA/DR parity is explicit.",
    confidenceImpact: "Confidence remains medium without parity proof.",
    automationPotential: "Medium: parity matrices can seed the KB.",
    sourceSection: "v2.1 / target / hadr",
  }),
  buildRule({
    id: "rule-tgt-synth-001",
    domainId: "domain-target-readiness",
    topicId: "topic-target-validation",
    ruleCode: "SE-TGT-SYN-001",
    title: "Synthetic workload test antes del go-live",
    severity: "critical",
    evidenceRequired: ["synthetic test", "owner", "result", "timestamp"],
    conditionText: "Sin test sintetico el target no puede declararse validado.",
    impact: "Evita asumir performance y conectividad por narracion.",
    remediation: "Ejecutar un synthetic workload test y documentar resultado.",
    scoringImpact: "Hard block until synthetic validation exists.",
    confidenceImpact: "Confidence remains low until synthetic test proof is visible.",
    automationPotential: "Medium: results can be parsed from test reports.",
    sourceSection: "v2.1 / target / synthetic",
  }),

  // Security
  buildRule({
    id: "rule-sec-secret-001",
    domainId: "domain-security",
    topicId: "topic-security-access",
    ruleCode: "SE-SEC-SEC-001",
    title: "Secretos y accesos deben quedar separados",
    severity: "critical",
    evidenceRequired: ["access map", "secret boundaries", "owner", "audit"],
    conditionText: "Una sola cuenta no debe concentrar accesos y secretos sensibles.",
    impact: "Reduce el riesgo de abuso o fuga de credenciales.",
    remediation: "Separar accesos, registrar owners y revisar secretos.",
    scoringImpact: "Blocks readiness while access boundaries are unclear.",
    confidenceImpact: "Confidence remains low until access separation is shown.",
    automationPotential: "Medium: access maps are structured and auditable.",
    sourceSection: "v2.1 / security / secrets",
  }),
  buildRule({
    id: "rule-sec-backup-001",
    domainId: "domain-security",
    topicId: "topic-security-backup",
    ruleCode: "SE-SEC-BKP-001",
    title: "Backup inmutable y recuperacion segura",
    severity: "critical",
    evidenceRequired: ["immutable backup", "restore proof", "owner", "retention"],
    conditionText: "Backup inmutable sin restore proof no es suficiente para seguridad.",
    impact: "Evita confiar en copias que aun no fueron probadas.",
    remediation: "Validar inmutabilidad y restore proof.",
    scoringImpact: "Hard block while backup recoverability is unknown.",
    confidenceImpact: "Confidence stays low until backup recovery is proven.",
    automationPotential: "Medium: backup systems expose structured proof.",
    sourceSection: "v2.1 / security / backup",
  }),
  buildRule({
    id: "rule-sec-imp-001",
    domainId: "domain-security",
    topicId: "topic-security-access",
    ruleCode: "SE-SEC-IMP-001",
    title: "Principio de minima exposicion",
    severity: "medium",
    evidenceRequired: ["least privilege", "network scope", "owner"],
    conditionText: "Los servicios de migracion no deben exponer mas superficie de la necesaria.",
    impact: "Minimiza impacto si una interfaz o credencial queda expuesta.",
    remediation: "Limitar scopes y rotar permisos innecesarios.",
    scoringImpact: "Moderate penalty if privilege scope is too broad.",
    confidenceImpact: "Confidence remains medium with broad exposure.",
    automationPotential: "Low: requires policy review and human sign-off.",
    sourceSection: "v2.1 / security / exposure",
  }),
  buildRule({
    id: "rule-sec-audit-001",
    domainId: "domain-security",
    topicId: "topic-security-access",
    ruleCode: "SE-SEC-AUD-001",
    title: "Audit logs y trazabilidad de acceso",
    severity: "high",
    evidenceRequired: ["audit log", "access trace", "owner"],
    conditionText: "Sin audit log no hay forma de explicar cambios criticos.",
    impact: "Reduce la confianza operativa y de compliance.",
    remediation: "Capturar logs y revisar cada cambio de acceso.",
    scoringImpact: "Readiness reduced until audit trail is available.",
    confidenceImpact: "Confidence remains bounded by audit coverage.",
    automationPotential: "High: audit logs are structured and machine-readable.",
    sourceSection: "v2.1 / security / audit",
  }),

  // Execution
  buildRule({
    id: "rule-exe-smoke-001",
    domainId: "domain-execution",
    topicId: "topic-execution-smoke",
    ruleCode: "SE-EXE-SMK-001",
    title: "Smoke test despues del corte",
    severity: "blocking",
    evidenceRequired: ["smoke suite", "owner", "timestamp", "result"],
    conditionText: "Un cutover sin smoke test no puede cerrarse como exito.",
    impact: "Evita asumir exito operativo sin validacion poscorte.",
    remediation: "Ejecutar smoke test y adjuntar resultado.",
    scoringImpact: "Hard block until smoke validation is green.",
    confidenceImpact: "Confidence remains low until smoke proof exists.",
    automationPotential: "High: test outputs can be ingested deterministically.",
    sourceSection: "v2.1 / execution / smoke",
  }),
  buildRule({
    id: "rule-exe-perf-001",
    domainId: "domain-execution",
    topicId: "topic-execution-smoke",
    ruleCode: "SE-EXE-PER-001",
    title: "Degradacion de performance debe quedar visible",
    severity: "critical",
    evidenceRequired: ["performance baseline", "after cutover", "owner"],
    conditionText: "Si la performance degrada, el plan debe tratarlo como riesgo real.",
    impact: "Evita ocultar el efecto del cambio en usuarios o apps.",
    remediation: "Comparar baseline y post-cutover y documentar gaps.",
    scoringImpact: "Performance degradation caps readiness.",
    confidenceImpact: "Confidence remains low while performance delta is open.",
    automationPotential: "Medium: performance reports can seed the KB.",
    sourceSection: "v2.1 / execution / performance",
  }),
  buildRule({
    id: "rule-exe-int-001",
    domainId: "domain-execution",
    topicId: "topic-execution-smoke",
    ruleCode: "SE-EXE-INT-001",
    title: "Falla de integracion abre rollback o remediation",
    severity: "critical",
    evidenceRequired: ["integration test", "owner", "rollback path"],
    conditionText: "Una integracion fallida no se debe tratar como incidente menor.",
    impact: "Puede detener la ola y exigir rollback.",
    remediation: "Tener rollback o remediation listo antes del corte.",
    scoringImpact: "Hard block when integration failure is unresolved.",
    confidenceImpact: "Confidence remains low until integration risk is closed.",
    automationPotential: "Medium: integration reports can be structured.",
    sourceSection: "v2.1 / execution / integration",
  }),
  buildRule({
    id: "rule-exe-hyper-001",
    domainId: "domain-execution",
    topicId: "topic-execution-hypercare",
    ruleCode: "SE-EXE-HYP-001",
    title: "Hypercare no cierra sin criterio definido",
    severity: "medium",
    evidenceRequired: ["hypercare plan", "owner", "closure criteria"],
    conditionText: "Hypercare sin criterio de cierre deja el corte abierto demasiado tiempo.",
    impact: "Extiende el riesgo operativo sin decision clara.",
    remediation: "Definir criterios de cierre y owner de hypercare.",
    scoringImpact: "Moderate penalty until hypercare closure is explicit.",
    confidenceImpact: "Confidence remains medium until hypercare is complete.",
    automationPotential: "Low: closure criteria require human judgement.",
    sourceSection: "v2.1 / execution / hypercare",
  }),
  buildRule({
    id: "rule-exe-wave-001",
    domainId: "domain-execution",
    topicId: "topic-execution-hypercare",
    ruleCode: "SE-EXE-WAV-001",
    title: "Secuencia de waves y congelamiento",
    severity: "high",
    evidenceRequired: ["wave plan", "freeze window", "owner"],
    conditionText: "Las waves no deben avanzar sin congelamiento y secuencia acordada.",
    impact: "Evita mover cargas criticas fuera de orden.",
    remediation: "Documentar wave sequence y freeze window.",
    scoringImpact: "Execution readiness reduced until waves are sequenced.",
    confidenceImpact: "Confidence remains medium while wave sequencing is open.",
    automationPotential: "High: wave plans are structured enough to seed the KB.",
    sourceSection: "v2.1 / execution / waves",
  }),

  // Remediation
  buildRule({
    id: "rule-rem-gap-001",
    domainId: "domain-remediation",
    topicId: "topic-remediation-queue",
    ruleCode: "SE-REM-GAP-001",
    title: "Cada gap debe tener owner y cierre",
    severity: "high",
    evidenceRequired: ["gap owner", "closure date", "status"],
    conditionText: "Un gap sin owner ni fecha de cierre sigue siendo bloqueante.",
    impact: "Evita que la deuda quede invisible.",
    remediation: "Asignar owner y fecha de reevaluacion.",
    scoringImpact: "Gaps keep readiness capped until owned.",
    confidenceImpact: "Confidence remains medium while the gap queue is open.",
    automationPotential: "Medium: remediation queue is easy to catalog.",
    sourceSection: "v2.1 / remediation / gaps",
  }),
  buildRule({
    id: "rule-rem-debt-002",
    domainId: "domain-remediation",
    topicId: "topic-remediation-debt",
    ruleCode: "SE-REM-DTB-002",
    title: "Deuda aceptada necesita expiracion y review",
    severity: "medium",
    evidenceRequired: ["debt expiry", "review date", "owner"],
    conditionText: "La deuda aceptada debe expirar o reevaluarse.",
    impact: "Evita normalizar un riesgo que ya no fue revisado.",
    remediation: "Poner expiracion y review date.",
    scoringImpact: "Accepted debt still reduces readiness.",
    confidenceImpact: "Confidence remains bounded until debt is rechecked.",
    automationPotential: "Low: requires human review cadence.",
    sourceSection: "v2.1 / remediation / debt",
  }),
  buildRule({
    id: "rule-rem-plan-001",
    domainId: "domain-remediation",
    topicId: "topic-remediation-queue",
    ruleCode: "SE-REM-PLN-001",
    title: "Plan de remediation debe estar priorizado",
    severity: "medium",
    evidenceRequired: ["priority", "owner", "impact"],
    conditionText: "Sin priorizacion no hay forma de cerrar el gap de manera controlada.",
    impact: "Evita una cola de remediacion sin orden operativo.",
    remediation: "Priorizar por impacto y dependencia.",
    scoringImpact: "Readiness improves only when remediation is sequenced.",
    confidenceImpact: "Confidence remains medium with unprioritized remediation.",
    automationPotential: "Medium: queue items can be structured and tracked.",
    sourceSection: "v2.1 / remediation / plan",
  }),
  buildRule({
    id: "rule-rem-accept-001",
    domainId: "domain-remediation",
    topicId: "topic-remediation-debt",
    ruleCode: "SE-REM-ACC-001",
    title: "Aceptar deuda no equivale a cerrar el riesgo",
    severity: "high",
    evidenceRequired: ["risk acceptance", "owner", "expiry"],
    conditionText: "Aceptar deuda solo mueve el riesgo, no lo borra.",
    impact: "Evita malinterpretar el estado del proyecto.",
    remediation: "Registrar el riesgo residual y su dueño.",
    scoringImpact: "Accepted debt lowers but does not remove the penalty.",
    confidenceImpact: "Confidence remains constrained until the debt is retired.",
    automationPotential: "Low: risk acceptance needs human review.",
    sourceSection: "v2.1 / remediation / acceptance",
  }),

  // Checklists
  buildRule({
    id: "rule-check-gate-001",
    domainId: "domain-checklists",
    topicId: "topic-checklists-governance",
    ruleCode: "SE-CHK-GAT-001",
    title: "Checklist de gates con owner y timestamp",
    severity: "high",
    evidenceRequired: ["owner", "timestamp", "gate status"],
    conditionText: "Sin owner y timestamp un checklist no puede considerarse completo.",
    impact: "Evita falsos positivos de completitud.",
    remediation: "Pedir el owner y registrar el momento de cierre.",
    scoringImpact: "Checklist does not advance readiness by itself.",
    confidenceImpact: "Confidence remains medium with incomplete checklist items.",
    automationPotential: "High: checklist items are deterministic.",
    sourceSection: "v2.1 / checklists / gates",
  }),
  buildRule({
    id: "rule-check-post-001",
    domainId: "domain-checklists",
    topicId: "topic-checklists-postcutover",
    ruleCode: "SE-CHK-PST-001",
    title: "Post-cutover cleanup y handoff",
    severity: "medium",
    evidenceRequired: ["cleanup", "handoff", "owner", "closure"],
    conditionText: "Un post-cutover sin handoff sigue dejando el trabajo abierto.",
    impact: "Evita confundir actividad con cierre real.",
    remediation: "Documentar cleanup, handoff y cierre.",
    scoringImpact: "Moderate penalty until post-cutover closure exists.",
    confidenceImpact: "Confidence remains medium until handoff closes.",
    automationPotential: "Low: closure is mostly human driven.",
    sourceSection: "v2.1 / checklists / postcutover",
  }),
];

export const METHODOLOGY_EXPANDED_KNOWLEDGE_CHUNKS: MethodologyKnowledgeChunk[] = [
  buildChunk({
    id: "chunk-governance-trace",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-trace",
    sourceDocumentId: "doc-scoring-appendix",
    chunkKey: "governance.rule-trace-expanded",
    title: "Trace y override auditables",
    content:
      "Toda regla debe dejar un trace legible: que se vio, que se overrideo, quien decidio y cual es la vigencia. Un resultado sin trace no es suficiente para apoyar a Advisor, scoring o PDF.",
    tags: ["trace", "override", "audit", "rule"],
    intendedUse: "admin",
    relatedRuleCodes: ["SE-GOV-TRC-002", "SE-GOV-OVR-001"],
  }),
  buildChunk({
    id: "chunk-governance-gates",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-gates",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "governance.gates-extended",
    title: "Gates G0-G5 y deuda aceptada",
    content:
      "Los gates G0-G5 y la deuda aceptada deben aparecer en cualquier resumen ejecutivo. La KB debe explicar si un gap se bloqueo, se acepto o sigue abierto.",
    tags: ["gates", "debt", "override", "go-no-go"],
    intendedUse: "report",
    relatedRuleCodes: ["SE-GOV-GAT-002", "SE-GOV-DTB-001"],
  }),
  buildChunk({
    id: "chunk-governance-safety",
    domainId: "domain-governance-scoring",
    topicId: "topic-governance-claims",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "governance.claims-safety",
    title: "Claim safety para advisor y PDF",
    content:
      "Claims absolutos como guaranteed migration, zero downtime o replaces consultant deben reescribirse con limites, evidencia y follow-up.",
    tags: ["claims", "advisor", "sales", "safe wording"],
    intendedUse: "sales",
    relatedRuleCodes: ["SE-GOV-SCL-001", "SE-GOV-CONF-001"],
  }),
  buildChunk({
    id: "chunk-vmware-cpu",
    domainId: "domain-vmware",
    topicId: "topic-vmware-cpu",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "vmware.cpu-sizing",
    title: "CPU y sizing VMware",
    content:
      "CPU debe evaluarse con baseline, peak trend y host headroom. Sin oversubscription y workload profile no hay suficiente contexto para mover el workload.",
    tags: ["cpu", "sizing", "host headroom", "vmware"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-VMW-CPU-001", "SE-VMW-HST-001"],
  }),
  buildChunk({
    id: "chunk-vmware-network",
    domainId: "domain-vmware",
    topicId: "topic-vmware-network",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "vmware.network-health",
    title: "Network y health VMware",
    content:
      "Portgroups, vSwitch, MTU y warnings de vHealth deben ser visibles antes de dar por confiable la red VMware. Los warnings no son ruido: son parte del score.",
    tags: ["network", "vhealth", "mtu", "portgroup"],
    intendedUse: "scoring",
    relatedRuleCodes: ["SE-VMW-NET-001", "SE-VMW-VHL-001"],
  }),
  buildChunk({
    id: "chunk-vmware-licensing",
    domainId: "domain-vmware",
    topicId: "topic-vmware-network",
    sourceDocumentId: "doc-security-notes",
    chunkKey: "vmware.licensing",
    title: "Licensing y maintenance visibility",
    content:
      "Licenses tied to host or CPU, plus maintenance mode windows, must be explicit. A migration can be technically valid and still fail on licensing or host scheduling.",
    tags: ["licensing", "maintenance", "host", "compliance"],
    intendedUse: "sales",
    relatedRuleCodes: ["SE-VMW-LIC-001", "SE-VMW-HST-001"],
  }),
  buildChunk({
    id: "chunk-proxmox-kvm",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-kvm",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "proxmox.kvm-lxc",
    title: "KVM, QEMU y LXC target baseline",
    content:
      "Proxmox readiness requires KVM/QEMU compatibility plus separate rules for LXC. Containers are not just smaller VMs and need their own mapping.",
    tags: ["proxmox", "kvm", "lxc", "compatibility"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-PVE-KVM-001", "SE-PVE-LXC-001", "SE-PVE-NET-001"],
  }),
  buildChunk({
    id: "chunk-proxmox-backup",
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-backup",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "proxmox.backup-restore",
    title: "PBS y restore proof",
    content:
      "PBS and backup target claims only count if restore proof exists. If restore evidence is missing, the target can still be promising but cannot be declared ready.",
    tags: ["pbs", "backup", "restore proof", "target"],
    intendedUse: "report",
    relatedRuleCodes: ["SE-PVE-PBS-001", "SE-TGT-BKP-001"],
  }),
  buildChunk({
    id: "chunk-san-resilience",
    domainId: "domain-san-storage",
    topicId: "topic-san-resilience",
    sourceDocumentId: "doc-scoring-appendix",
    chunkKey: "san.resilience",
    title: "SAN resilience and cache protection",
    content:
      "Multipath, cache protection and replication lag are separate signals. A SAN can look nominal and still be a migration risk if any of these are unknown.",
    tags: ["san", "multipath", "cache", "replication"],
    intendedUse: "scoring",
    relatedRuleCodes: ["SE-SAN-MPT-001", "SE-SAN-CAC-001", "SE-SAN-REP-001"],
  }),
  buildChunk({
    id: "chunk-san-capacity",
    domainId: "domain-san-storage",
    topicId: "topic-san-capacity",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "san.capacity-runway",
    title: "Capacity runway and degradation",
    content:
      "Capacity runway should be described together with growth trend and degradation indicators. Nominal capacity alone is not enough for a safe go/no-go.",
    tags: ["capacity", "runway", "growth", "degradation"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-SAN-CAP-001"],
  }),
  buildChunk({
    id: "chunk-network-transport",
    domainId: "domain-networking",
    topicId: "topic-network-transport",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "network.transport",
    title: "LACP, MLAG y MTU",
    content:
      "Transport rules should explain link aggregation, failover and MTU consistency. If a route is not proven end to end, do not claim network readiness.",
    tags: ["lacp", "mlag", "mtu", "transport"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-NET-LAC-001", "SE-NET-MTU-001", "SE-NET-CAP-001"],
  }),
  buildChunk({
    id: "chunk-network-overlay",
    domainId: "domain-networking",
    topicId: "topic-network-overlay",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "network.overlay",
    title: "Overlay, routing and NAT",
    content:
      "Overlay networks and NAT rules need an explicit mapping to the migration lanes. A clear routing table is worth more than a vague statement that the network is ready.",
    tags: ["overlay", "routing", "nat", "sdn"],
    intendedUse: "report",
    relatedRuleCodes: ["SE-NET-ROU-001", "SE-NET-OVL-001"],
  }),
  buildChunk({
    id: "chunk-app-stateful",
    domainId: "domain-applications",
    topicId: "topic-app-stateful",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "applications.stateful",
    title: "Stateful apps and shared services",
    content:
      "Stateful apps, shared services and fixed-IP integrations need owner sign-off and a sequencing plan. The migration can be technically sound and still fail on application coupling.",
    tags: ["stateful", "shared services", "fixed ip", "sla"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-APP-STA-001", "SE-APP-SHR-001", "SE-APP-FIP-001", "SE-APP-SLA-001"],
  }),
  buildChunk({
    id: "chunk-app-licensing",
    domainId: "domain-applications",
    topicId: "topic-app-licensing",
    sourceDocumentId: "doc-security-notes",
    chunkKey: "applications.licensing",
    title: "Licensing tied to hardware or CPU",
    content:
      "Licensing terms tied to CPU or host identity must be reviewed before the target is declared safe. Compliance issues can be just as blocking as technical gaps.",
    tags: ["licensing", "cpu", "host", "compliance"],
    intendedUse: "sales",
    relatedRuleCodes: ["SE-APP-LIC-001"],
  }),
  buildChunk({
    id: "chunk-target-compute",
    domainId: "domain-target-readiness",
    topicId: "topic-target-compute",
    sourceDocumentId: "doc-scoring-appendix",
    chunkKey: "target.compute-headroom",
    title: "Compute headroom for the target",
    content:
      "Target compute readiness should summarize CPU, RAM and growth forecast. If the target cannot absorb the workload with margin, readiness stays capped.",
    tags: ["cpu", "ram", "headroom", "forecast"],
    intendedUse: "scoring",
    relatedRuleCodes: ["SE-TGT-CMP-001", "SE-TGT-STR-001"],
  }),
  buildChunk({
    id: "chunk-target-validation",
    domainId: "domain-target-readiness",
    topicId: "topic-target-validation",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "target.validation",
    title: "Validation on the target",
    content:
      "Synthetic tests, backup proof and HA/DR parity are the kind of target validations that turn readiness into something defendable.",
    tags: ["synthetic", "backup", "ha", "dr"],
    intendedUse: "report",
    relatedRuleCodes: ["SE-TGT-NET-001", "SE-TGT-BKP-001", "SE-TGT-HDR-001", "SE-TGT-SYN-001"],
  }),
  buildChunk({
    id: "chunk-security-access",
    domainId: "domain-security",
    topicId: "topic-security-access",
    sourceDocumentId: "doc-security-notes",
    chunkKey: "security.access-boundaries",
    title: "Access boundaries and audit logs",
    content:
      "Security notes should keep access boundaries and audit logs visible. Least privilege and secret separation are mandatory for a safe migration.",
    tags: ["access", "audit", "secrets", "least privilege"],
    intendedUse: "admin",
    relatedRuleCodes: ["SE-SEC-SEC-001", "SE-SEC-IMP-001", "SE-SEC-AUD-001"],
  }),
  buildChunk({
    id: "chunk-security-backup",
    domainId: "domain-security",
    topicId: "topic-security-backup",
    sourceDocumentId: "doc-security-notes",
    chunkKey: "security.backup-recovery",
    title: "Backup and recovery security",
    content:
      "Immutable backup and restore proof must be treated as a security boundary, not a checkbox. Recovery without proof is only a promise.",
    tags: ["backup", "immutable", "restore proof", "recovery"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-SEC-BKP-001"],
  }),
  buildChunk({
    id: "chunk-execution-smoke",
    domainId: "domain-execution",
    topicId: "topic-execution-smoke",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "execution.smoke-performance",
    title: "Smoke, performance and integration failure",
    content:
      "A cutover only counts after smoke tests, performance deltas and integration failures are resolved. If any of those remain open, the rollout is not done.",
    tags: ["smoke", "performance", "integration", "rollback"],
    intendedUse: "report",
    relatedRuleCodes: ["SE-EXE-SMK-001", "SE-EXE-PER-001", "SE-EXE-INT-001"],
  }),
  buildChunk({
    id: "chunk-execution-hypercare",
    domainId: "domain-execution",
    topicId: "topic-execution-hypercare",
    sourceDocumentId: "doc-checklist-ops",
    chunkKey: "execution.hypercare",
    title: "Hypercare closure and waves",
    content:
      "Wave sequencing and hypercare closure should stay visible until the owner confirms the post-cutover state is stable and complete.",
    tags: ["hypercare", "waves", "closure", "post-cutover"],
    intendedUse: "advisor",
    relatedRuleCodes: ["SE-EXE-HYP-001", "SE-EXE-WAV-001"],
  }),
  buildChunk({
    id: "chunk-remediation-queue",
    domainId: "domain-remediation",
    topicId: "topic-remediation-queue",
    sourceDocumentId: "doc-remediation-catalog",
    chunkKey: "remediation.queue",
    title: "Remediation queue and accepted debt",
    content:
      "A remediation queue must carry owner, due date and the scope of accepted debt. Without those fields, the debt can look closed while the risk remains open.",
    tags: ["remediation", "debt", "owner", "expiry"],
    intendedUse: "admin",
    relatedRuleCodes: ["SE-REM-GAP-001", "SE-REM-PLN-001", "SE-REM-DTB-002", "SE-REM-ACC-001"],
  }),
  buildChunk({
    id: "chunk-checklists",
    domainId: "domain-checklists",
    topicId: "topic-checklists-governance",
    sourceDocumentId: "doc-checklist-ops",
    chunkKey: "checklists.gates",
    title: "Gate and post-cutover checklists",
    content:
      "Checklists should cover gate ownership, timestamping and post-cutover handoff. A checklist without closure is just a reminder, not evidence.",
    tags: ["checklist", "gate", "handoff", "closure"],
    intendedUse: "all",
    relatedRuleCodes: ["SE-CHK-GAT-001", "SE-CHK-PST-001"],
  }),
];

const METHODOLOGY_EXPANDED_CHANGE_LOG_SEEDS: ChangeLogSeed[] = [
  {
    id: "log-2026-06-06-methodology-3-governance",
    entityType: "topic",
    entityId: "topic-governance-trace",
    changeType: "expanded",
    summary: "Se agregan trace, gates y claim safety a la gobernanza.",
    rationale: "Ampliar el lenguaje de auditabilidad y claims seguros.",
    createdBy: "system-seed",
    createdAt: "2026-06-06T08:00:00.000Z",
  },
  {
    id: "log-2026-06-06-methodology-3-platforms",
    entityType: "domain",
    entityId: "domain-vmware",
    changeType: "expanded",
    summary: "Se suman CPU, network, licensing y host coverage para VMware.",
    rationale: "Cubrir mas senales operativas antes del bridge a Advisor/PDF.",
    createdBy: "system-seed",
    createdAt: "2026-06-06T09:00:00.000Z",
  },
  {
    id: "log-2026-06-06-methodology-3-target",
    entityType: "domain",
    entityId: "domain-proxmox",
    changeType: "expanded",
    summary: "Se amplian KVM, LXC, Ceph, PBS y target validation.",
    rationale: "Hacer mas util la KB para readout tecnico del target.",
    createdBy: "system-seed",
    createdAt: "2026-06-06T10:00:00.000Z",
  },
  {
    id: "log-2026-06-06-methodology-3-execution",
    entityType: "domain",
    entityId: "domain-execution",
    changeType: "expanded",
    summary: "Se agregan smoke, performance, integration y hypercare.",
    rationale: "Preparar el bridge hacia reportes y advisor con wording seguro.",
    createdBy: "system-seed",
    createdAt: "2026-06-06T11:00:00.000Z",
  },
];

export const METHODOLOGY_EXPANDED_CHANGE_LOG: MethodologyChangeLogEntry[] = METHODOLOGY_EXPANDED_CHANGE_LOG_SEEDS.map(
  (entry) => ({
    ...entry,
    versionId: VERSION_ID,
  }),
);
