import type {
  MethodologyAdminNote,
  MethodologyChangeLogEntry,
  MethodologyDomain,
  MethodologyKnowledgeChunk,
  MethodologyRecordStatus,
  MethodologyRule,
  MethodologySourceDocument,
  MethodologyTopic,
  MethodologyVersion,
} from "./types";

const VERSION_ID = "methodology_v2_1";
const BASE_TIME = "2026-06-06T00:00:00.000Z";

const baseTimestamps = {
  createdAt: BASE_TIME,
  updatedAt: BASE_TIME,
};

export const METHODOLOGY_VERSION: MethodologyVersion = {
  id: VERSION_ID,
  versionLabel: "Shift Evidence Methodology Bible v2.1",
  title: "Methodology Knowledge Base",
  status: "active",
  sourceDocumentName: "Shift Evidence Methodology Bible v2.1",
  effectiveFrom: "2026-06-01T00:00:00.000Z",
  notes:
    "Read-only TypeScript seed for the Methodology Knowledge Base admin foundation. No Prisma migration required.",
  createdAt: BASE_TIME,
  updatedAt: BASE_TIME,
};

export const METHODOLOGY_DOMAINS: MethodologyDomain[] = [
  {
    id: "domain-governance-scoring",
    versionId: VERSION_ID,
    key: "governance_scoring",
    label: "Gobernanza, score dual y confianza",
    description: "Normas para separar readiness, evidence score y confidence sin mezclar signals.",
    order: 1,
  },
  {
    id: "domain-vmware",
    versionId: VERSION_ID,
    key: "vmware",
    label: "VMware",
    description: "Inventario, snapshots, memoria, storage y backup para fuentes VMware.",
    order: 2,
  },
  {
    id: "domain-proxmox",
    versionId: VERSION_ID,
    key: "proxmox_ve",
    label: "Proxmox VE",
    description: "Target readiness, cluster baseline, storage y control de cutover para PVE.",
    order: 3,
  },
  {
    id: "domain-san-storage",
    versionId: VERSION_ID,
    key: "san_storage",
    label: "SAN y storage",
    description: "Fabric, multipath, latencia, capacidad y resiliencia de storage compartido.",
    order: 4,
  },
  {
    id: "domain-networking",
    versionId: VERSION_ID,
    key: "networking",
    label: "Red y segmentacion",
    description: "VLAN, L2/L3, MTU, firewall y aislamiento operativo para la migracion.",
    order: 5,
  },
  {
    id: "domain-applications",
    versionId: VERSION_ID,
    key: "applications_dependencies",
    label: "Aplicaciones y dependencias",
    description: "Owner sign-off, dependencias funcionales y ventanas de compatibilidad.",
    order: 6,
  },
  {
    id: "domain-target-readiness",
    versionId: VERSION_ID,
    key: "target_readiness",
    label: "Readiness del target",
    description: "Capacidad, performance, quotas y validaciones del destino antes del go/no-go.",
    order: 7,
  },
  {
    id: "domain-security",
    versionId: VERSION_ID,
    key: "migration_security",
    label: "Seguridad e inmutabilidad",
    description: "Separacion de funciones, inmutabilidad de backups y restricciones de acceso.",
    order: 8,
  },
  {
    id: "domain-execution",
    versionId: VERSION_ID,
    key: "execution_cutover_rollback",
    label: "Cutover y rollback",
    description: "Secuencia de ejecucion, gates G0-G5, rollback A/B y criterios de paro.",
    order: 9,
  },
  {
    id: "domain-remediation",
    versionId: VERSION_ID,
    key: "remediation_catalog",
    label: "Catalogo de remediaciones",
    description: "Patrones de remediacion aceptados para cerrar gaps sin improvisacion.",
    order: 10,
  },
  {
    id: "domain-checklists",
    versionId: VERSION_ID,
    key: "operational_checklists",
    label: "Checklists operativos",
    description: "Checklist de salida, validacion y post-cutover para evitar pasos omitidos.",
    order: 11,
  },
];

export const METHODOLOGY_TOPICS: MethodologyTopic[] = [
  {
    id: "topic-score-dual",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    key: "score-dual",
    title: "Score dual",
    summary: "Separar readiness score de evidence score para evitar sobrepromesas.",
    order: 1,
  },
  {
    id: "topic-confidence",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    key: "confidence",
    title: "Confidence y missing evidence",
    summary: "La confianza baja cuando faltan evidencias o hay bloqueos activos.",
    order: 2,
  },
  {
    id: "topic-vmware-storage",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    key: "vmware-storage",
    title: "Storage VMware",
    summary: "Datastores, latencia y crecimiento de storage.",
    order: 3,
  },
  {
    id: "topic-vmware-backup",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    key: "vmware-backup",
    title: "Backup y restore VMware",
    summary: "Copia, retencion y restauracion validada antes del cutover.",
    order: 4,
  },
  {
    id: "topic-proxmox-cluster",
    versionId: VERSION_ID,
    domainId: "domain-proxmox",
    key: "proxmox-cluster",
    title: "Cluster PVE",
    summary: "Quorum, HA y compatibilidad del cluster target.",
    order: 5,
  },
  {
    id: "topic-san-fabric",
    versionId: VERSION_ID,
    domainId: "domain-san-storage",
    key: "san-fabric",
    title: "SAN fabric",
    summary: "Zoning, paths, multipath y latencia del plano de storage.",
    order: 6,
  },
  {
    id: "topic-network-l2",
    versionId: VERSION_ID,
    domainId: "domain-networking",
    key: "network-l2",
    title: "Red L2/L3",
    summary: "VLAN, MTU, rutas y firewall para la nueva plataforma.",
    order: 7,
  },
  {
    id: "topic-app-deps",
    versionId: VERSION_ID,
    domainId: "domain-applications",
    key: "app-dependencies",
    title: "Dependencias y owner sign-off",
    summary: "Mapeo de dependencias, ventanas y aprobaciones funcionales.",
    order: 8,
  },
  {
    id: "topic-target-capacity",
    versionId: VERSION_ID,
    domainId: "domain-target-readiness",
    key: "target-capacity",
    title: "Capacidad del target",
    summary: "CPU, RAM, IOPS y headroom operacional.",
    order: 9,
  },
  {
    id: "topic-security-immutability",
    versionId: VERSION_ID,
    domainId: "domain-security",
    key: "security-immutability",
    title: "Inmutabilidad y acceso",
    summary: "Separacion de funciones y backup inmutable sin acceso directo a secretos.",
    order: 10,
  },
  {
    id: "topic-cutover-rollback",
    versionId: VERSION_ID,
    domainId: "domain-execution",
    key: "cutover-rollback",
    title: "Cutover y rollback",
    summary: "Plan A/B, gates, congelamiento y criterio de reversa.",
    order: 11,
  },
  {
    id: "topic-remediation",
    versionId: VERSION_ID,
    domainId: "domain-remediation",
    key: "remediation-catalog",
    title: "Catalogo de remediaciones",
    summary: "Criterios para aceptar deuda tecnica o ejecutar remediacion.",
    order: 12,
  },
  {
    id: "topic-checklists",
    versionId: VERSION_ID,
    domainId: "domain-checklists",
    key: "operational-checklists",
    title: "Checklists",
    summary: "Listas de control para preparacion, corte y validacion.",
    order: 13,
  },
];

function ruleTimestamps() {
  return {
    createdAt: baseTimestamps.createdAt,
    updatedAt: baseTimestamps.updatedAt,
  };
}

const activeRuleSurfaces = ["advisor", "scoring", "documentation", "pdf", "rag", "admin"] as const;

export const METHODOLOGY_RULES: MethodologyRule[] = [
  {
    id: "rule-gov-score-dual",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    topicId: "topic-score-dual",
    ruleCode: "SE-GOV-SCR-001",
    title: "Mantener score dual separado",
    severity: "blocking",
    evidenceRequired: ["readiness score", "evidence score", "confidence score"],
    conditionText:
      "No mezclar disponibilidad de evidencias con readiness operacional. Un score no valida al otro.",
    impact: "Evita que un buen score oculto compense evidencia incompleta.",
    remediation: "Publicar ambas dimensiones por separado y explicar la brecha entre ellas.",
    scoringImpact: "Divide readiness y evidence score; no eleva confidence sin soporte.",
    confidenceImpact: "Confidence bounded by the weakest evidence lane.",
    automationPotential: "High: el preview puede derivar dos scores independientes.",
    sourceSection: "v2.1 / governance / score dual",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-gov-confidence",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    topicId: "topic-confidence",
    ruleCode: "SE-GOV-CONF-001",
    title: "La confianza no puede exceder la evidencia",
    severity: "critical",
    evidenceRequired: ["missing evidence list", "owner sign-off", "assessment summary"],
    conditionText:
      "Si falta evidencia o hay bloqueos activos, la confidence no puede declararse alta ni cerrada.",
    impact: "Previene overclaiming y evita mover proyectos con zonas ciegas.",
    remediation: "Declarar evidencia faltante y reabrir la validacion sobre los gaps.",
    scoringImpact: "Cap confidence at medium while blockers remain open.",
    confidenceImpact: "Confidence queda limitada por missing evidence.",
    automationPotential: "Medium: el motor puede detectar faltantes y limitar confidence.",
    sourceSection: "v2.1 / governance / confidence",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-gov-evidence",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    topicId: "topic-confidence",
    ruleCode: "SE-GOV-EVID-001",
    title: "La ausencia de evidencia no es evidencia positiva",
    severity: "critical",
    evidenceRequired: ["missing evidence log", "explicit negative findings", "timestamped source"],
    conditionText: "No asumir readiness por silencio, ausencia de alertas o datos incompletos.",
    impact: "Evita conclusiones optimistas cuando el dataset esta incompleto.",
    remediation: "Marcar la brecha como bloqueante y pedir la evidencia concreta que falta.",
    scoringImpact: "Missing evidence keeps readiness below go/no-go threshold.",
    confidenceImpact: "Confidence remains low until evidence is explicit.",
    automationPotential: "High: el validador puede clasificar silencios como gaps.",
    sourceSection: "v2.1 / governance / missing evidence",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-vmw-sto-001",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-storage",
    ruleCode: "SE-VMW-STO-001",
    title: "Inventario de storage VMware y tendencia de crecimiento",
    severity: "critical",
    evidenceRequired: ["datastore list", "latency metrics", "growth trend", "capacity headroom"],
    conditionText:
      "Sin inventario de datastores, latencia y crecimiento, no se puede asumir readiness de storage VMware.",
    impact: "Puede ocultar saturacion, I/O contention y ventanas de migracion extendidas.",
    remediation: "Recolectar inventario completo y tendencia 30/90 dias antes de cerrar el readiness.",
    scoringImpact: "Storage readiness capped until inventory and trend are confirmed.",
    confidenceImpact: "Confidence queda en medium o menos hasta validar la capacidad.",
    automationPotential: "High: el inventario puede alimentar la KB de forma deterministica.",
    sourceSection: "v2.1 / VMware / storage",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-vmw-snp-001",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-storage",
    ruleCode: "SE-VMW-SNP-001",
    title: "Snapshots de VMware deben estar inventariados y controlados",
    severity: "high",
    evidenceRequired: ["snapshot inventory", "age", "owner", "cleanup plan"],
    conditionText: "Snapshots viejos o sin due date elevan riesgo de performance y rollback confuso.",
    impact: "Snapshots acumulados pueden degradar performance y complicar la reversa.",
    remediation: "Inventariar, limpiar y documentar excepciones con owner y fecha.",
    scoringImpact: "Penalize readiness when snapshots are stale or unmanaged.",
    confidenceImpact: "Reduce confidence until cleanup or sign-off is visible.",
    automationPotential: "Medium: exports y reports pueden detectar snapshots pendientes.",
    sourceSection: "v2.1 / VMware / snapshots",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-vmw-ram-001",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-storage",
    ruleCode: "SE-VMW-RAM-001",
    title: "Memoria, ballooning y swap deben estar dentro del baseline",
    severity: "medium",
    evidenceRequired: ["memory usage", "ballooning", "swap", "peak trend"],
    conditionText: "Ballooning persistente o swap alto obligan a revisar sizing antes de migrar.",
    impact: "El target podria heredar contention de RAM o sizing insuficiente.",
    remediation: "Revisar allocation, peak usage y umbrales de swap antes del cutover.",
    scoringImpact: "Moderate penalty on readiness if RAM metrics are outside baseline.",
    confidenceImpact: "Confidence drops if peak memory use is unexplained.",
    automationPotential: "High: metrics de performance pueden alimentar la regla.",
    sourceSection: "v2.1 / VMware / memory",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-vmw-bkp-001",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-backup",
    ruleCode: "SE-VMW-BKP-001",
    title: "Backup actualizado y consistente para VMware",
    severity: "critical",
    evidenceRequired: ["backup job status", "last successful run", "retention", "scope"],
    conditionText: "No se puede aprobar readiness si el backup esta vencido, incompleto o sin cobertura.",
    impact: "Sin backup vigente, cualquier incidente de cutover se convierte en riesgo operativo alto.",
    remediation: "Validar jobs, retencion y scope; marcar excepciones con owner.",
    scoringImpact: "Backup readiness blocks go/no-go when runs are stale or missing.",
    confidenceImpact: "Confidence should not exceed medium while backup is stale.",
    automationPotential: "High: job histories pueden poblar la KB.",
    sourceSection: "v2.1 / VMware / backup",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-vmw-bkp-004",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-backup",
    ruleCode: "SE-VMW-BKP-004",
    title: "Restore de backup validado antes del go/no-go",
    severity: "blocking",
    evidenceRequired: ["restore test", "timestamped proof", "restore owner", "result"],
    conditionText: "Un backup sin restore test no puede considerarse evidencia suficiente.",
    impact: "Evita que el proyecto avance con backups no verificados o no restaurables.",
    remediation: "Ejecutar restore test documentado y adjuntar evidencia.",
    scoringImpact: "Hard block until restore evidence exists.",
    confidenceImpact: "Confidence remains low until restore proof is present.",
    automationPotential: "Medium: puede detectar el artefacto de prueba y su fecha.",
    sourceSection: "v2.1 / VMware / restore test",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-pve-cls-001",
    versionId: VERSION_ID,
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-cluster",
    ruleCode: "SE-PVE-CLS-001",
    title: "Cluster Proxmox con quorum y compatibilidad validada",
    severity: "critical",
    evidenceRequired: ["quorum status", "cluster nodes", "storage compatibility", "maintenance plan"],
    conditionText: "No declarar target ready sin quorum sano y compatibilidad de cluster confirmada.",
    impact: "Un cluster inestable rompe la premisa de migracion segura.",
    remediation: "Validar quorum, nodos y plan de mantenimiento por adelantado.",
    scoringImpact: "Target readiness blocked until cluster baseline is green.",
    confidenceImpact: "Confidence bounded by quorum and cluster health.",
    automationPotential: "High: el estado del cluster se puede traer desde exports.",
    sourceSection: "v2.1 / Proxmox VE / cluster",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-pve-sto-001",
    versionId: VERSION_ID,
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-cluster",
    ruleCode: "SE-PVE-STO-001",
    title: "Storage target Proxmox con capacidad y rendimiento",
    severity: "high",
    evidenceRequired: ["storage layout", "capacity headroom", "latency", "datastore map"],
    conditionText: "El target necesita espacio y performance reales, no solo capacidad nominal.",
    impact: "Storage mal dimensionado genera cuellos de botella post-cutover.",
    remediation: "Comparar capacidad nominal, uso real y crecimiento esperado.",
    scoringImpact: "Penalize target readiness when headroom is thin.",
    confidenceImpact: "Confidence lowers if storage layout is incomplete.",
    automationPotential: "High: capacity maps and health metrics can seed the KB.",
    sourceSection: "v2.1 / Proxmox VE / storage",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-san-fab-001",
    versionId: VERSION_ID,
    domainId: "domain-san-storage",
    topicId: "topic-san-fabric",
    ruleCode: "SE-SAN-FAB-001",
    title: "Fabric SAN, zoning y multipath deben estar limpios",
    severity: "critical",
    evidenceRequired: ["fabric diagram", "zoning matrix", "multipath status", "latency baseline"],
    conditionText: "Sin fabric estable y multipath correcto, el storage del target queda expuesto.",
    impact: "Puede introducir fallos intermitentes, path flapping o degradacion de IO.",
    remediation: "Validar zoning, paths activos y latencia antes del corte.",
    scoringImpact: "Blocks storage readiness until fabric is confirmed.",
    confidenceImpact: "Confidence should not be high when fabric is uncertain.",
    automationPotential: "Medium: collects from health checks and switch exports.",
    sourceSection: "v2.1 / SAN / fabric",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-sec-imm-001",
    versionId: VERSION_ID,
    domainId: "domain-security",
    topicId: "topic-security-immutability",
    ruleCode: "SE-SEC-IMM-001",
    title: "Separacion de funciones e inmutabilidad obligatorias",
    severity: "critical",
    evidenceRequired: ["access separation", "immutable backup proof", "audit log", "owner sign-off"],
    conditionText:
      "No se puede dar por segura la migracion si una sola cuenta o persona concentra acceso, cambios y recuperacion.",
    impact: "Reduce el riesgo de cambios no auditados, borrado de evidencia o uso indebido de credenciales.",
    remediation: "Separar roles, validar inmutabilidad y registrar trazabilidad de acceso.",
    scoringImpact: "Blocks readiness when access control is not isolated.",
    confidenceImpact: "Confidence remains low until separation of duties is shown.",
    automationPotential: "Medium: logs y manifests pueden comprobar separacion e inmutabilidad.",
    sourceSection: "v2.1 / security / immutability",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-net-l2-001",
    versionId: VERSION_ID,
    domainId: "domain-networking",
    topicId: "topic-network-l2",
    ruleCode: "SE-NET-L2-001",
    title: "Red L2/L3, VLAN, MTU y firewall validados",
    severity: "critical",
    evidenceRequired: ["vlan map", "mtu validation", "routing path", "firewall exceptions"],
    conditionText: "No avanzar si la red target no tiene segmentacion y conectividad comprobadas.",
    impact: "Una red incompleta impide acceso, observabilidad y validacion post-cutover.",
    remediation: "Validar VLAN, MTU, rutas y reglas de firewall de forma previa.",
    scoringImpact: "Blocks go/no-go until network baseline is explicit.",
    confidenceImpact: "Confidence stays low until network evidence is complete.",
    automationPotential: "High: network inventories are structured and machine-readable.",
    sourceSection: "v2.1 / networking / L2-L3",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-app-dep-001",
    versionId: VERSION_ID,
    domainId: "domain-applications",
    topicId: "topic-app-deps",
    ruleCode: "SE-APP-DEP-001",
    title: "Dependencias aplicativas y owner sign-off",
    severity: "critical",
    evidenceRequired: ["dependency map", "owner sign-off", "window approval", "application criticality"],
    conditionText: "Las dependencias sin owner y sin ventana aprobada son bloqueantes.",
    impact: "Evita que la migracion rompa flujos invisibles o integraciones externas.",
    remediation: "Mapear dependencias y obtener confirmacion de los responsables.",
    scoringImpact: "Application readiness blocked by unresolved dependencies.",
    confidenceImpact: "Confidence cannot be declared high without owner sign-off.",
    automationPotential: "Medium: dependency graphs and forms can seed the KB.",
    sourceSection: "v2.1 / applications / dependencies",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-tgt-cap-001",
    versionId: VERSION_ID,
    domainId: "domain-target-readiness",
    topicId: "topic-target-capacity",
    ruleCode: "SE-TGT-CAP-001",
    title: "Capacidad del target con headroom operativo",
    severity: "critical",
    evidenceRequired: ["cpu headroom", "ram headroom", "iops headroom", "growth forecast"],
    conditionText: "Si el target no tiene headroom suficiente, no se declara listo para migrar.",
    impact: "Impide que el proyecto avance con una plataforma subdimensionada.",
    remediation: "Recalcular sizing y revisar limites antes del corte.",
    scoringImpact: "Hard block until target capacity is aligned with forecast.",
    confidenceImpact: "Confidence limited by capacity and growth data.",
    automationPotential: "High: target telemetry can be normalized into the KB.",
    sourceSection: "v2.1 / target / capacity",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
  {
    id: "rule-exe-rlb-001",
    versionId: VERSION_ID,
    domainId: "domain-execution",
    topicId: "topic-cutover-rollback",
    ruleCode: "SE-EXE-RLB-001",
    title: "Cutover con rollback A/B y gates G0-G5",
    severity: "blocking",
    evidenceRequired: ["gates G0-G5", "rollback A/B", "freeze window", "decision log"],
    conditionText: "La ejecucion debe tener gates y rollback antes de iniciar cualquier corte.",
    impact: "Reduce el riesgo de quedar sin reversa o sin criterio de abortar.",
    remediation: "Definir gates, rollback A/B y decision log antes del go-live.",
    scoringImpact: "Execution readiness blocked until rollback is explicit.",
    confidenceImpact: "Confidence remains bounded without rollback plan.",
    automationPotential: "Medium: el checklist puede inferir gate completion.",
    sourceSection: "v2.1 / execution / rollback",
    status: "active",
    usageSurface: [...activeRuleSurfaces],
    ...ruleTimestamps(),
  },
];

export const METHODOLOGY_SOURCE_DOCUMENTS: MethodologySourceDocument[] = [
  {
    id: "doc-bible-v2-1",
    versionId: VERSION_ID,
    title: "Shift Evidence Methodology Bible v2.1",
    filename: "shift-evidence-methodology-bible-v2.1.md",
    documentType: "bible",
    checksum: "seed-bible-v2-1",
    uploadedBy: "system-seed",
    status: "active",
    createdAt: BASE_TIME,
  },
  {
    id: "doc-scoring-appendix",
    versionId: VERSION_ID,
    title: "Scoring appendix",
    filename: "methodology-scoring-appendix-v2.1.md",
    documentType: "strategy",
    checksum: "seed-scoring-appendix",
    uploadedBy: "system-seed",
    status: "active",
    createdAt: BASE_TIME,
  },
  {
    id: "doc-cutover-runbook",
    versionId: VERSION_ID,
    title: "Cutover runbook",
    filename: "methodology-cutover-runbook-v2.1.md",
    documentType: "runbook",
    checksum: "seed-cutover-runbook",
    uploadedBy: "system-seed",
    status: "active",
    createdAt: BASE_TIME,
  },
  {
    id: "doc-checklist-ops",
    versionId: VERSION_ID,
    title: "Operational checklists",
    filename: "methodology-operational-checklists-v2.1.md",
    documentType: "checklist",
    checksum: "seed-ops-checklists",
    uploadedBy: "system-seed",
    status: "active",
    createdAt: BASE_TIME,
  },
  {
    id: "doc-remediation-catalog",
    versionId: VERSION_ID,
    title: "Remediation catalog",
    filename: "methodology-remediation-catalog-v2.1.md",
    documentType: "runbook",
    checksum: "seed-remediation-catalog",
    uploadedBy: "system-seed",
    status: "active",
    createdAt: BASE_TIME,
  },
  {
    id: "doc-security-notes",
    versionId: VERSION_ID,
    title: "Security and immutability notes",
    filename: "methodology-security-notes-v2.1.md",
    documentType: "note",
    checksum: "seed-security-notes",
    uploadedBy: "system-seed",
    status: "active",
    createdAt: BASE_TIME,
  },
];

export const METHODOLOGY_KNOWLEDGE_CHUNKS: MethodologyKnowledgeChunk[] = [
  {
    id: "chunk-governance-score-dual",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    topicId: "topic-score-dual",
    sourceDocumentId: "doc-scoring-appendix",
    chunkKey: "governance.score-dual",
    title: "Score dual y lectura separada",
    content:
      "El readiness score y el evidence score se publican por separado. Si uno sube y el otro baja, el informe debe reflejar la diferencia. No se puede convertir confidence en readiness por simple narracion.",
    tags: ["score dual", "confidence", "governance", "readiness"],
    intendedUse: "scoring",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-GOV-SCR-001", "SE-GOV-CONF-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-governance-missing-evidence",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    topicId: "topic-confidence",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "governance.missing-evidence",
    title: "Confidence y missing evidence",
    content:
      "La confianza solo puede crecer cuando la evidencia requerida esta presente. La ausencia de datos no cuenta como validacion positiva. Si hay evidencias faltantes, el sistema debe listar exactamente cuales faltan y evitar declarar el target listo.",
    tags: ["missing evidence", "confidence", "gates", "advisory"],
    intendedUse: "advisor",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-GOV-CONF-001", "SE-GOV-EVID-001", "SE-TGT-CAP-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-governance-rule-trace",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    topicId: "topic-confidence",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "governance.rule-trace",
    title: "Trace de reglas y overrides",
    content:
      "Todo resultado debe explicar que reglas aplicaron, cual fue el impacto y si hubo override humano. Los overrides solo se aceptan con justification, owner y fecha. Sin trazabilidad no hay cierre metodologico.",
    tags: ["rule trace", "override", "audit", "admin"],
    intendedUse: "admin",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-GOV-SCR-001", "SE-GOV-EVID-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-execution-gates",
    versionId: VERSION_ID,
    domainId: "domain-execution",
    topicId: "topic-cutover-rollback",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "execution.gates",
    title: "Gates G0-G5 para cutover",
    content:
      "Los gates G0 a G5 ordenan la preparacion, validacion, congelamiento, corte, verificacion y decision de rollback. Cada gate debe tener owner, timestamp y evidencia de completitud.",
    tags: ["gates", "G0", "G5", "cutover"],
    intendedUse: "report",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-EXE-RLB-001", "SE-APP-DEP-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-execution-rollback-ab",
    versionId: VERSION_ID,
    domainId: "domain-execution",
    topicId: "topic-cutover-rollback",
    sourceDocumentId: "doc-cutover-runbook",
    chunkKey: "execution.rollback-ab",
    title: "Rollback A/B y decision log",
    content:
      "El plan de rollback debe definir A/B, condiciones de retorno, responsable de decision y canal de comunicacion. Un cutover sin rollback definido no puede considerarse listo.",
    tags: ["rollback", "A/B", "decision log", "freeze"],
    intendedUse: "advisor",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-EXE-RLB-001", "SE-GOV-CONF-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-vmware-backup-restore",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-backup",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "vmware.backup-restore",
    title: "Backup y restore VMware",
    content:
      "Los backups solo cuentan cuando existe un restore test confirmado, con evidencia de fecha, owner y resultado. RVTools u otra fuente de inventario no reemplaza la prueba de restauracion.",
    tags: ["backup", "restore", "rvtools", "vmware"],
    intendedUse: "advisor",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-VMW-BKP-001", "SE-VMW-BKP-004"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-vmware-storage-health",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    topicId: "topic-vmware-storage",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "vmware.storage-health",
    title: "VMware storage health",
    content:
      "El inventario de datastores, la latencia y la tendencia de crecimiento deben ser visibles antes del corte. Un storage sano sin tendencia no basta para declarar capacidad suficiente.",
    tags: ["datastore", "latency", "growth", "storage"],
    intendedUse: "scoring",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-VMW-STO-001", "SE-VMW-RAM-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-proxmox-target",
    versionId: VERSION_ID,
    domainId: "domain-proxmox",
    topicId: "topic-proxmox-cluster",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "proxmox.target-baseline",
    title: "Proxmox target baseline",
    content:
      "El target Proxmox necesita quorum estable, layout de storage claro y una ventana de mantenimiento que no pise dependencias criticas. Capacidad nominal sin headroom no alcanza.",
    tags: ["proxmox", "quorum", "capacity", "cluster"],
    intendedUse: "advisor",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-PVE-CLS-001", "SE-PVE-STO-001", "SE-TGT-CAP-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-network-segmentation",
    versionId: VERSION_ID,
    domainId: "domain-networking",
    topicId: "topic-network-l2",
    sourceDocumentId: "doc-bible-v2-1",
    chunkKey: "network.segmentation",
    title: "Segmentacion de red y firewall",
    content:
      "La validacion de red incluye VLAN, MTU, rutas y excepciones de firewall. Si cualquier ruta o segmentacion falta, el target no puede declararse listo.",
    tags: ["vlan", "mtu", "firewall", "routing"],
    intendedUse: "advisor",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-NET-L2-001", "SE-SEC-IMM-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-remediation-catalog",
    versionId: VERSION_ID,
    domainId: "domain-remediation",
    topicId: "topic-remediation",
    sourceDocumentId: "doc-remediation-catalog",
    chunkKey: "remediation.catalog",
    title: "Catalogo de remediaciones aceptadas",
    content:
      "Cuando faltan evidencias, el catalogo define acciones aceptadas: recolectar metricas, ejecutar restore test, documentar owner, o diferir la decision con deuda tecnica aceptada.",
    tags: ["remediation", "debt", "accepted", "catalog"],
    intendedUse: "admin",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-GOV-EVID-001", "SE-EXE-RLB-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
  {
    id: "chunk-operational-checklists",
    versionId: VERSION_ID,
    domainId: "domain-checklists",
    topicId: "topic-checklists",
    sourceDocumentId: "doc-checklist-ops",
    chunkKey: "operations.checklists",
    title: "Checklists operativos",
    content:
      "Los checklists cubren preparacion, freeze, cutover, verificacion y post-cutover. Ningun paso puede marcarse completo sin owner, timestamp y evidencia de ejecucion.",
    tags: ["checklist", "freeze", "post-cutover", "owner"],
    intendedUse: "report",
    embeddingStatus: "indexed",
    status: "active",
    relatedRuleCodes: ["SE-EXE-RLB-001", "SE-GOV-SCR-001"],
    createdAt: BASE_TIME,
    updatedAt: BASE_TIME,
  },
];

export const METHODOLOGY_CHANGE_LOG: MethodologyChangeLogEntry[] = [
  {
    id: "log-2026-06-01-seed",
    versionId: VERSION_ID,
    entityType: "version",
    entityId: VERSION_ID,
    changeType: "created",
    summary: "Se inicializa la KB v2.1 read-only en TypeScript.",
    rationale: "Foundation segura sin migracion de DB ni cambios de runtime.",
    createdBy: "system-seed",
    createdAt: "2026-06-01T08:00:00.000Z",
  },
  {
    id: "log-2026-06-02-governance",
    versionId: VERSION_ID,
    entityType: "domain",
    entityId: "domain-governance-scoring",
    changeType: "expanded",
    summary: "Se agregan score dual, confidence y missing evidence.",
    rationale: "Evitar overclaiming y separar readiness de evidence score.",
    createdBy: "system-seed",
    createdAt: "2026-06-02T08:00:00.000Z",
  },
  {
    id: "log-2026-06-02-vmware",
    versionId: VERSION_ID,
    entityType: "domain",
    entityId: "domain-vmware",
    changeType: "expanded",
    summary: "Se fijan reglas de storage, snapshots y backup restore.",
    rationale: "Cubrir las fuentes de evidencia mas criticas para migracion.",
    createdBy: "system-seed",
    createdAt: "2026-06-02T11:00:00.000Z",
  },
  {
    id: "log-2026-06-03-target",
    versionId: VERSION_ID,
    entityType: "domain",
    entityId: "domain-proxmox",
    changeType: "expanded",
    summary: "Se consolidan reglas de cluster y capacity para Proxmox.",
    rationale: "Preparar un target con capacidad real y quorum validado.",
    createdBy: "system-seed",
    createdAt: "2026-06-03T09:30:00.000Z",
  },
  {
    id: "log-2026-06-04-execution",
    versionId: VERSION_ID,
    entityType: "topic",
    entityId: "topic-cutover-rollback",
    changeType: "expanded",
    summary: "Se formalizan gates G0-G5 y rollback A/B.",
    rationale: "La ejecucion requiere decision tree y reversa trazable.",
    createdBy: "system-seed",
    createdAt: "2026-06-04T10:45:00.000Z",
  },
  {
    id: "log-2026-06-05-remediation",
    versionId: VERSION_ID,
    entityType: "topic",
    entityId: "topic-remediation",
    changeType: "expanded",
    summary: "Se agrega catalogo de remediaciones aceptadas.",
    rationale: "Evitar improvisacion y anclar decisiones administrativas.",
    createdBy: "system-seed",
    createdAt: "2026-06-05T12:20:00.000Z",
  },
];

export const METHODOLOGY_ADMIN_NOTES: MethodologyAdminNote[] = [
  {
    id: "note-1",
    versionId: VERSION_ID,
    title: "Write path deferred",
    content:
      "La escritura de notas se habilitara en METHODOLOGY-2 para evitar cambios de DB no auditados.",
    priority: "high",
    status: "open",
    createdAt: "2026-06-06T07:00:00.000Z",
    updatedAt: "2026-06-06T07:00:00.000Z",
  },
  {
    id: "note-2",
    versionId: VERSION_ID,
    domainId: "domain-governance-scoring",
    title: "Score dual visible in admin",
    content: "Mostrar score dual en admin pero mantenerlo read-only hasta conectar scoring live.",
    priority: "normal",
    status: "incorporated",
    createdAt: "2026-06-04T07:00:00.000Z",
    updatedAt: "2026-06-05T07:00:00.000Z",
  },
  {
    id: "note-3",
    versionId: VERSION_ID,
    domainId: "domain-vmware",
    title: "Restore proof required",
    content: "No aceptar backup completion como evidencia suficiente sin restore test fechado.",
    priority: "critical",
    status: "open",
    createdAt: "2026-06-05T09:15:00.000Z",
    updatedAt: "2026-06-05T09:15:00.000Z",
  },
  {
    id: "note-4",
    versionId: VERSION_ID,
    topicId: "topic-cutover-rollback",
    title: "Rollback A/B must stay visible",
    content: "El panel admin debe exponer gates y rollback sin ocultar las condiciones de paro.",
    priority: "high",
    status: "open",
    createdAt: "2026-06-05T13:40:00.000Z",
    updatedAt: "2026-06-05T13:40:00.000Z",
  },
];

export const METHODOLOGY_FEATURE_NOTES = [
  "Read-only foundation. No Prisma migration, no production cutover, no payments or Wise touched.",
  "All records are deterministic TypeScript seeds so the admin console can render without DB writes.",
  "The advisory service can reuse these rules later, but the live Advisor flow remains unchanged for now.",
  "METHODOLOGY-2 can add persistence for notes, edits, embeddings, and review workflow after audit.",
];

export const METHODOLOGY_SEED = {
  version: METHODOLOGY_VERSION,
  domains: METHODOLOGY_DOMAINS,
  topics: METHODOLOGY_TOPICS,
  rules: METHODOLOGY_RULES,
  sourceDocuments: METHODOLOGY_SOURCE_DOCUMENTS,
  knowledgeChunks: METHODOLOGY_KNOWLEDGE_CHUNKS,
  changeLog: METHODOLOGY_CHANGE_LOG,
  notes: METHODOLOGY_ADMIN_NOTES,
  featureNotes: METHODOLOGY_FEATURE_NOTES,
} as const;

export function getMethodologySeedVersionId() {
  return VERSION_ID;
}

export function isMethodologyRecordStatus(value: string): value is MethodologyRecordStatus {
  return value === "draft" || value === "active" || value === "archived";
}
