import { type AssessmentDetail } from "./assessmentService";
import {
  getCostRiskStatus,
  getLicensingCostContextFromAssessment,
  getStorageAnalysisContextFromAssessment,
} from "./costRiskService";
import { buildInfrastructureStatus } from "./infrastructureInputService";
import {
  computeMigrationContextCoverage,
  getMigrationContextFromAssessment,
} from "./migrationContextService";
import { getEvidenceUploadStatus } from "../evidence/evidenceFileService";
import { getParsedInventorySnapshot } from "../rvtools/rvtoolsInventoryService";
import {
  getLatestReportForAssessment,
  getReportPreviewStatusFromReports,
} from "../reports/reportHistoryService";

export type CompletionStatus = "missing" | "partial" | "complete";

export type AssessmentModuleKey =
  | "rvtools_inventory"
  | "infrastructure_risk"
  | "migration_questions"
  | "storage_analysis"
  | "licensing_cost_exposure"
  | "manual_assumptions"
  | "ai_advisory"
  | "report_generation";

export type AssessmentModuleStatus =
  | "not_started"
  | "in_progress"
  | "partial"
  | "complete"
  | "skipped"
  | "not_applicable"
  | "blocked"
  | "failed"
  | "unknown";

export type AssessmentCompletionPrimaryCta =
  | "upload_rvtools"
  | "generate_report"
  | "improve_report"
  | "review_modules";

export type AssessmentCompletionEvidence = {
  count?: number;
  source?: string;
  lastUpdatedAt?: Date | string | null;
};

export type AssessmentCompletionModule = {
  key: AssessmentModuleKey;
  label: string;
  description: string;
  required: boolean;
  status: AssessmentModuleStatus;
  weight: number;
  confidenceContribution: number;
  completionContribution: number;
  actionLabel?: string;
  impactIfMissing?: string;
  limitationText?: string;
  evidence?: AssessmentCompletionEvidence;
};

export type AssessmentCompletionSummary = {
  completionPercent: number;
  reportConfidencePercent: number;
  requiredComplete: boolean;
  canGenerateReport: boolean;
  modules: AssessmentCompletionModule[];
  missingRequired: AssessmentCompletionModule[];
  missingRecommended: AssessmentCompletionModule[];
  limitations: string[];
  primaryCta: AssessmentCompletionPrimaryCta;
};

type CompletionModuleDefinition = {
  key: AssessmentModuleKey;
  label: string;
  description: string;
  required: boolean;
  weight: number;
  actionLabel: string;
  impactIfMissing: string;
};

export const assessmentCompletionModuleCatalog = [
  {
    key: "rvtools_inventory",
    label: "RVTools Inventory",
    description: "Base technical evidence for the VMware inventory.",
    required: true,
    weight: 35,
    actionLabel: "Upload RVTools",
    impactIfMissing:
      "A serious technical report requires parsed VMware inventory evidence.",
  },
  {
    key: "infrastructure_risk",
    label: "Infrastructure Risk Analysis",
    description: "Risk findings generated from the parsed infrastructure data.",
    required: true,
    weight: 15,
    actionLabel: "Review infrastructure risk",
    impactIfMissing:
      "Risk sequencing remains limited until infrastructure findings are available.",
  },
  {
    key: "migration_questions",
    label: "Migration Questions",
    description: "Business context, goals, urgency, criticality and constraints.",
    required: false,
    weight: 10,
    actionLabel: "Answer migration questions",
    impactIfMissing:
      "The report can be generated, but business context and prioritization will be less precise.",
  },
  {
    key: "storage_analysis",
    label: "Storage Analysis",
    description: "Current and target storage context across SAN, NAS, vSAN, Ceph or ZFS.",
    required: false,
    weight: 15,
    actionLabel: "Add storage context",
    impactIfMissing:
      "Storage recommendations remain estimated and require manual validation.",
  },
  {
    key: "licensing_cost_exposure",
    label: "Licensing & Cost Exposure",
    description: "VMware and Proxmox cost inputs, renewal exposure and modeled savings.",
    required: false,
    weight: 15,
    actionLabel: "Add cost assumptions",
    impactIfMissing:
      "Financial exposure and savings should be treated as directional only.",
  },
  {
    key: "manual_assumptions",
    label: "Manual Assumptions",
    description: "Constraints, deadlines, budget, criticality and manual technical notes.",
    required: false,
    weight: 5,
    actionLabel: "Add assumptions",
    impactIfMissing:
      "Manual constraints and exceptions may be underrepresented in the report.",
  },
  {
    key: "ai_advisory",
    label: "AI Advisory",
    description: "Narrative recommendations generated by AI as a non-blocking advisory layer.",
    required: false,
    weight: 3,
    actionLabel: "Generate AI advisory",
    impactIfMissing:
      "The report remains usable, but advisory narrative may rely on deterministic sections only.",
  },
  {
    key: "report_generation",
    label: "Report Generation",
    description: "Preview or final assessment report generated from available evidence.",
    required: true,
    weight: 2,
    actionLabel: "Generate report",
    impactIfMissing:
      "The assessment has not yet produced a deliverable report.",
  },
] as const satisfies readonly CompletionModuleDefinition[];

export type AssessmentCompletionAssessmentInput = Partial<AssessmentDetail> & {
  aiUsageEvents?: Array<{
    status?: string | null;
    fallbackUsed?: boolean | null;
    createdAt?: Date | string | null;
    updatedAt?: Date | string | null;
  }>;
};

export function getAssessmentCompletionStatus(assessment: AssessmentDetail) {
  const infrastructureStatus = buildInfrastructureStatus(assessment.infrastructureInput);
  const costAssumptionsStatus = getCostRiskStatus(assessment);
  const storageStatus = assessment.storageReadinessEnabled
    ? assessment.storageReadinessInput
      ? "selected"
      : "pending"
    : "skipped";
  const rvtoolsStatus = getEvidenceUploadStatus(assessment);
  const inventorySnapshot = getParsedInventorySnapshot(assessment);
  const inventoryStatus = inventorySnapshot?.inventoryStatus ?? "not_available";
  const evidenceConfidence = inventorySnapshot?.evidenceConfidence ?? "limited";
  const previewReady = Boolean(assessment.preliminaryResult);
  const pdfStatus = getReportPreviewStatusFromReports(assessment);
  const hasReportPreviewSignals =
    previewReady ||
    inventoryStatus !== "not_available" ||
    Boolean(assessment.assessmentScore) ||
    (assessment.riskFindings?.length ?? 0) > 0;
  const reportPreviewStatus =
    hasReportPreviewSignals ? (inventoryStatus === "parsed" ? "available" : "partial") : "locked";

  const score =
    (infrastructureStatus === "complete" ? 35 : infrastructureStatus === "partial" ? 20 : 0) +
    (costAssumptionsStatus === "complete" ? 35 : costAssumptionsStatus === "partial" ? 20 : 0) +
    (previewReady ? 20 : 0) +
    (storageStatus === "skipped" || storageStatus === "selected" ? 10 : 0) +
    (rvtoolsStatus === "uploaded" || rvtoolsStatus === "parsed" ? 10 : 0) +
    (inventoryStatus === "parsed" ? 10 : inventoryStatus === "partial" ? 5 : 0);

  const completionStatus: CompletionStatus =
    score >= 80 ? "complete" : score >= 40 ? "partial" : "missing";

  return {
    infrastructureStatus,
    costAssumptionsStatus,
    storageStatus,
    rvtoolsStatus,
    inventoryStatus,
    evidenceConfidence,
    reportPreviewStatus,
    fullReportStatus: "locked" as const,
    pdfStatus,
    reportStatus: "locked" as const,
    completionScore: Math.min(score, 100),
    completionStatus,
  };
}

export function getMissingEvidenceSummary(assessment: AssessmentDetail) {
  const completion = getAssessmentCompletionStatus(assessment);
  const preview = assessment.preliminaryResult;
  const inventoryStatus = completion.inventoryStatus;

  const missing: string[] = [];

  if (completion.infrastructureStatus !== "complete") {
    missing.push("Complete the manual infrastructure intake.");
  }

  if (completion.costAssumptionsStatus !== "complete") {
    missing.push("Finish the Cost / Risk assumptions.");
  }

  if (completion.storageStatus === "pending") {
    missing.push("Decide whether Storage Destination Readiness is needed.");
  }

  if (!preview) {
    missing.push("Generate the preliminary cost and risk preview.");
  }

  if (inventoryStatus !== "not_available" && !assessment.assessmentScore) {
    missing.push("Generate inventory-driven risk insights.");
  }

  if (completion.rvtoolsStatus === "not_uploaded_yet") {
    missing.push("Upload RVTools evidence to prepare for the future parser.");
  } else if (completion.rvtoolsStatus === "deleted") {
    missing.push("Re-upload RVTools evidence if you need the parser-ready workflow.");
  } else if (completion.rvtoolsStatus === "uploaded") {
    missing.push("Parse RVTools evidence to create a preliminary inventory.");
  } else if (completion.rvtoolsStatus === "failed") {
    missing.push("Reparse RVTools evidence after fixing the parsing issue.");
  }

  return missing;
}

export function getNextStepsSummary(assessment: AssessmentDetail) {
  const completion = getAssessmentCompletionStatus(assessment);

  const steps = [
    "Upload RVTools evidence when you are ready for the next milestone.",
    completion.rvtoolsStatus === "uploaded"
      ? "Run the basic RVTools parser to create a preliminary inventory."
      : completion.rvtoolsStatus === "parsed"
        ? "Review the preliminary inventory and parser warnings."
        : "Review the preliminary inventory once parsing is complete.",
    inventoryStatusHasScore(assessment)
      ? "Review inventory-driven risk findings and readiness scores."
      : "Generate inventory-driven risk insights when the parsed inventory is ready.",
    "Complete Cost / Risk assumptions.",
    "Review missing evidence before making a migration decision.",
  ];

  if (completion.storageStatus === "pending") {
    steps.splice(1, 0, "Decide whether to add Storage Destination Readiness.");
  }

  if (completion.completionStatus === "complete") {
    steps.push("Use the preview as a preliminary signal, not a final report.");
  }

  return steps;
}

function inventoryStatusHasScore(assessment: AssessmentDetail) {
  return Boolean(getParsedInventorySnapshot(assessment)) && Boolean(assessment.assessmentScore);
}

type ModuleDetectionResult = {
  status: AssessmentModuleStatus;
  evidence?: AssessmentCompletionEvidence;
  limitationText?: string;
};

type ModuleDetectionContext = {
  assessment: AssessmentCompletionAssessmentInput;
  rvtoolsStatus?: AssessmentModuleStatus;
  reportStatus?: AssessmentModuleStatus;
};

const COMPLETE_STATUSES = new Set<AssessmentModuleStatus>(["complete", "not_applicable"]);

const RECOMMENDED_MISSING_STATUSES = new Set<AssessmentModuleStatus>([
  "not_started",
  "in_progress",
  "partial",
  "skipped",
  "blocked",
  "failed",
  "unknown",
]);

function clampPercent(value: number) {
  return Math.max(0, Math.min(100, Math.round(value)));
}

function getCompletionCredit(status: AssessmentModuleStatus, weight: number) {
  if (status === "complete" || status === "not_applicable" || status === "skipped") {
    return weight;
  }

  if (status === "partial") {
    return weight * 0.5;
  }

  if (status === "in_progress") {
    return weight * 0.35;
  }

  return 0;
}

function getConfidenceCredit(status: AssessmentModuleStatus, weight: number) {
  if (status === "complete" || status === "not_applicable") {
    return weight;
  }

  if (status === "partial") {
    return weight * 0.5;
  }

  if (status === "in_progress") {
    return weight * 0.35;
  }

  return 0;
}

function buildCompletionModule(
  definition: CompletionModuleDefinition,
  detection: ModuleDetectionResult,
): AssessmentCompletionModule {
  return {
    key: definition.key,
    label: definition.label,
    description: definition.description,
    required: definition.required,
    status: detection.status,
    weight: definition.weight,
    confidenceContribution: clampPercent(
      getConfidenceCredit(detection.status, definition.weight),
    ),
    completionContribution: clampPercent(
      getCompletionCredit(detection.status, definition.weight),
    ),
    actionLabel: definition.actionLabel,
    impactIfMissing: definition.impactIfMissing,
    limitationText: detection.limitationText,
    evidence: detection.evidence,
  };
}

function getActiveRvtoolsEvidence(assessment: AssessmentCompletionAssessmentInput) {
  return (assessment.evidenceFiles ?? []).filter(
    (file) =>
      file.evidenceType === "rvtools" &&
      file.deletedAt === null &&
      file.processingStatus !== "deleted",
  );
}

function getLatestDate(values: Array<Date | string | null | undefined>) {
  const timestamps = values
    .filter((value): value is Date | string => value !== null && value !== undefined)
    .map((value) => new Date(value).getTime())
    .filter(Number.isFinite);

  if (timestamps.length === 0) {
    return null;
  }

  return new Date(Math.max(...timestamps));
}

function hasMeaningfulValue(value: unknown) {
  if (value === null || value === undefined) {
    return false;
  }

  if (typeof value === "string") {
    return value.trim().length > 0;
  }

  if (typeof value === "number") {
    return Number.isFinite(value);
  }

  if (typeof value === "boolean") {
    return true;
  }

  if (Array.isArray(value)) {
    return value.length > 0;
  }

  if (value instanceof Date) {
    return Number.isFinite(value.getTime());
  }

  if (typeof value === "object") {
    return Object.keys(value).length > 0;
  }

  return false;
}

function countMeaningfulValues(values: unknown[]) {
  return values.filter(hasMeaningfulValue).length;
}

function detectRvtoolsInventoryModule(
  assessment: AssessmentCompletionAssessmentInput,
): ModuleDetectionResult {
  const evidenceFiles = getActiveRvtoolsEvidence(assessment);
  const evidenceStatus = getEvidenceUploadStatus(assessment as AssessmentDetail);
  const inventorySnapshot = getParsedInventorySnapshot(assessment as AssessmentDetail);
  const latestEvidence = evidenceFiles.at(-1);
  const evidence: AssessmentCompletionEvidence = {
    count: evidenceFiles.length,
    source: latestEvidence?.originalFilename,
    lastUpdatedAt: getLatestDate(evidenceFiles.map((file) => file.uploadedAt)),
  };

  if (inventorySnapshot?.inventoryStatus === "parsed") {
    return { status: "complete", evidence };
  }

  if (inventorySnapshot?.inventoryStatus === "partial") {
    return {
      status: "partial",
      evidence,
      limitationText:
        "RVTools inventory was parsed with warnings, so some infrastructure evidence may need manual validation.",
    };
  }

  if (evidenceStatus === "uploaded") {
    return {
      status: "in_progress",
      evidence,
      limitationText:
        "RVTools evidence is uploaded but the parsed inventory is not complete yet.",
    };
  }

  if (evidenceStatus === "failed" || inventorySnapshot?.inventoryStatus === "failed") {
    return {
      status: "failed",
      evidence,
      limitationText:
        "RVTools evidence could not be parsed successfully, so the technical report cannot rely on inventory data yet.",
    };
  }

  return {
    status: "not_started",
    evidence,
    limitationText:
      "RVTools inventory is required before a serious migration readiness report can be generated.",
  };
}

function detectInfrastructureRiskModule({
  assessment,
  rvtoolsStatus,
}: ModuleDetectionContext): ModuleDetectionResult {
  const findingsCount = assessment.riskFindings?.length ?? 0;

  if (findingsCount > 0 || assessment.assessmentScore) {
    return {
      status: "complete",
      evidence: {
        count: findingsCount,
        source: findingsCount > 0 ? "risk_findings" : "assessment_score",
        lastUpdatedAt: getLatestDate(
          (assessment.riskFindings ?? []).map(
            (finding) => finding.updatedAt ?? finding.createdAt,
          ),
        ),
      },
    };
  }

  if (rvtoolsStatus === "complete" || rvtoolsStatus === "partial") {
    return {
      status: "partial",
      evidence: { count: 0, source: "parsed_inventory" },
      limitationText:
        "Inventory evidence exists, but generated risk findings are not complete yet.",
    };
  }

  if (rvtoolsStatus === "failed") {
    return {
      status: "blocked",
      evidence: { count: 0 },
      limitationText:
        "Infrastructure risk analysis is blocked until RVTools inventory can be parsed.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: 0 },
    limitationText:
      "Infrastructure risk analysis starts after inventory evidence is available.",
  };
}

function detectMigrationQuestionsModule(
  assessment: AssessmentCompletionAssessmentInput,
): ModuleDetectionResult {
  const context = getMigrationContextFromAssessment(assessment as AssessmentDetail);
  const coverage = computeMigrationContextCoverage(context);

  if (coverage.status === "strong") {
    return {
      status: "complete",
      evidence: {
        count: coverage.answeredWeight,
        source: "migration_context",
        lastUpdatedAt: context.updatedAt,
      },
    };
  }

  if (coverage.status === "partial" || coverage.status === "limited") {
    return {
      status: "partial",
      evidence: {
        count: coverage.answeredWeight,
        source: "migration_context",
        lastUpdatedAt: context.updatedAt,
      },
      limitationText:
        "Migration goals, constraints or criticality are only partially documented.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: 0, source: "migration_context" },
    limitationText:
      "Business context is missing, so the report cannot fully explain urgency, sequencing or stakeholder priorities.",
  };
}

function detectStorageAnalysisModule(
  assessment: AssessmentCompletionAssessmentInput,
): ModuleDetectionResult {
  const storageInput = assessment.storageReadinessInput;
  const storageContext = getStorageAnalysisContextFromAssessment(assessment as AssessmentDetail);
  const parsedDatastoreCount =
    (assessment.parsedDatastores?.length ?? 0) +
    (assessment.parsedInventorySummaries ?? []).reduce(
      (total, summary) => total + (summary.datastoreCount ?? 0),
      0,
    );
  const storageFieldCount = countMeaningfulValues([
    storageInput?.currentStorageType,
    storageInput?.targetStoragePreference,
    storageInput?.capacityTb,
    storageInput?.usedTb,
    storageInput?.expectedGrowthPercent,
    storageInput?.requiresHa,
    storageInput?.requiresSharedStorage,
    storageInput?.workloadProfile,
    storageInput?.performanceSensitivity,
    storageInput?.operationalComplexityTolerance,
    storageInput?.notes,
  ]);
  const storageContextFieldCount = countMeaningfulValues([
    storageContext.currentStorageType,
    storageContext.targetStoragePreference,
    storageContext.knownConstraints,
    storageContext.notes,
  ]);
  const evidenceSource = storageContextFieldCount > 0 ? "storage_context" : "storage_readiness";

  if (storageContext.decision === "not_applicable") {
    return {
      status: "not_applicable",
      evidence: { count: parsedDatastoreCount, source: "storage_context" },
    };
  }

  if (storageContext.decision === "skipped") {
    return {
      status: "skipped",
      evidence: { count: parsedDatastoreCount, source: "storage_context" },
      limitationText:
        "Storage Analysis was skipped, so storage recommendations should be treated as estimates from RVTools datastore evidence only.",
    };
  }

  const hasStorageContextCore =
    Boolean(storageContext.currentStorageType) &&
    Boolean(storageContext.targetStoragePreference) &&
    (storageContext.knownConstraints.length > 0 ||
      Boolean(storageContext.notes) ||
      parsedDatastoreCount > 0);

  if (hasStorageContextCore || (storageFieldCount >= 4 && parsedDatastoreCount > 0)) {
    return {
      status: "complete",
      evidence: { count: parsedDatastoreCount, source: evidenceSource },
    };
  }

  if (storageContextFieldCount > 0 || storageFieldCount > 0 || parsedDatastoreCount > 0) {
    return {
      status: "partial",
      evidence: { count: parsedDatastoreCount, source: evidenceSource },
      limitationText:
        "Storage evidence exists, but target storage assumptions or operational constraints are incomplete.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: 0, source: "storage_readiness" },
    limitationText:
      "Storage analysis is not completed, so storage recommendations require manual validation.",
  };
}

function detectLicensingCostExposureModule(
  assessment: AssessmentCompletionAssessmentInput,
): ModuleDetectionResult {
  const costRiskStatus = getCostRiskStatus(assessment as AssessmentDetail);
  const assumptions = assessment.costRiskAssumptions;
  const licensingContext = getLicensingCostContextFromAssessment(assessment as AssessmentDetail);
  const evidenceCount = countMeaningfulValues([
    assumptions?.vmwareLicenseModel,
    assumptions?.annualVmwareCost,
    assumptions?.estimatedProxmoxCost,
    licensingContext.renewalTimeframe,
    licensingContext.includeProxmoxEstimate,
    licensingContext.notes,
  ]);

  if (licensingContext.decision === "not_applicable") {
    return {
      status: "not_applicable",
      evidence: { count: evidenceCount, source: "licensing_context" },
    };
  }

  if (licensingContext.decision === "skipped") {
    return {
      status: "skipped",
      evidence: { count: evidenceCount, source: "licensing_context" },
      limitationText:
        "Licensing & Cost Exposure was skipped, so renewal exposure and savings should be treated as directional USD estimates.",
    };
  }

  if (costRiskStatus === "complete" || evidenceCount >= 4) {
    return {
      status: "complete",
      evidence: { count: evidenceCount, source: "cost_risk_assumptions" },
    };
  }

  if (evidenceCount > 0) {
    return {
      status: "partial",
      evidence: { count: evidenceCount, source: "cost_risk_assumptions" },
      limitationText:
        "Cost exposure is partially modeled; financial figures should be treated as directional USD estimates.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: evidenceCount, source: "cost_risk_assumptions" },
    limitationText:
      "Licensing and cost exposure are missing, so ROI and renewal exposure are not fully supported.",
  };
}

function detectManualAssumptionsModule(
  assessment: AssessmentCompletionAssessmentInput,
): ModuleDetectionResult {
  const infrastructure = assessment.infrastructureInput;
  const assumptions = assessment.costRiskAssumptions;
  const fieldCount = countMeaningfulValues([
    infrastructure?.criticalWorkloadCount,
    infrastructure?.largeVmCount,
    infrastructure?.poweredOffVmCount,
    infrastructure?.storageFootprintTb,
    infrastructure?.usedStorageTb,
    infrastructure?.notes,
    assumptions?.migrationComplexity,
    assumptions?.businessCriticality,
    assumptions?.riskTolerance,
    assumptions?.assumptionsJson,
  ]);

  if (fieldCount >= 5) {
    return {
      status: "complete",
      evidence: { count: fieldCount, source: "manual_assumptions" },
    };
  }

  if (fieldCount > 0) {
    return {
      status: "partial",
      evidence: { count: fieldCount, source: "manual_assumptions" },
      limitationText:
        "Manual assumptions are only partially documented, so exceptions and constraints may need follow-up.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: 0, source: "manual_assumptions" },
    limitationText:
      "Manual assumptions are missing, so deadlines, constraints and exceptions may not be reflected.",
  };
}

function detectAiAdvisoryModule({
  assessment,
  reportStatus,
}: ModuleDetectionContext): ModuleDetectionResult {
  const events = assessment.aiUsageEvents ?? [];
  const successfulEvent = events.find((event) =>
    ["success", "mock", "fallback"].includes(String(event.status ?? "")),
  );
  const failedEvent = events.find((event) =>
    ["error", "timeout", "unavailable"].includes(String(event.status ?? "")),
  );

  if (successfulEvent || events.some((event) => event.fallbackUsed === true)) {
    return {
      status: "complete",
      evidence: {
        count: events.length,
        source: "ai_usage_events",
        lastUpdatedAt: getLatestDate(events.map((event) => event.updatedAt ?? event.createdAt)),
      },
    };
  }

  if (failedEvent) {
    return {
      status: "failed",
      evidence: {
        count: events.length,
        source: "ai_usage_events",
        lastUpdatedAt: failedEvent.updatedAt ?? failedEvent.createdAt,
      },
      limitationText:
        "AI advisory failed or timed out; the assessment should rely on deterministic analysis sections.",
    };
  }

  if (reportStatus === "complete") {
    return {
      status: "partial",
      evidence: { count: 0, source: "report_generation" },
      limitationText:
        "A report exists, but AI advisory evidence was not available in the assessment detail payload.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: 0, source: "ai_usage_events" },
    limitationText:
      "AI advisory has not been generated. This does not block the report.",
  };
}

function detectReportGenerationModule(
  assessment: AssessmentCompletionAssessmentInput,
): ModuleDetectionResult {
  const latestReport = getLatestReportForAssessment(assessment as AssessmentDetail);
  const previewStatus = getReportPreviewStatusFromReports(assessment as AssessmentDetail);

  if (latestReport?.status === "generated" || previewStatus === "generated") {
    return {
      status: "complete",
      evidence: {
        count: (assessment.reports ?? []).filter(
          (report) => report.deletedAt === null && report.status === "generated",
        ).length,
        source: latestReport?.reportType ?? "report",
        lastUpdatedAt:
          latestReport?.generatedAt ?? latestReport?.updatedAt ?? latestReport?.createdAt,
      },
    };
  }

  if (latestReport?.status === "generating" || previewStatus === "generating") {
    return {
      status: "in_progress",
      evidence: { count: assessment.reports?.length ?? 0, source: "report" },
      limitationText:
        "Report generation is in progress and the deliverable is not ready yet.",
    };
  }

  if (latestReport?.status === "failed" || previewStatus === "failed") {
    return {
      status: "failed",
      evidence: { count: assessment.reports?.length ?? 0, source: "report" },
      limitationText:
        "The last report generation attempt failed and should be retried after reviewing evidence.",
    };
  }

  if (assessment.preliminaryResult) {
    return {
      status: "partial",
      evidence: { count: 1, source: "preliminary_result" },
      limitationText:
        "A preliminary result exists, but no active final report is available yet.",
    };
  }

  return {
    status: "not_started",
    evidence: { count: 0, source: "report" },
    limitationText: "No report has been generated yet.",
  };
}

function detectModule(
  definition: CompletionModuleDefinition,
  context: ModuleDetectionContext,
): ModuleDetectionResult {
  switch (definition.key) {
    case "rvtools_inventory":
      return detectRvtoolsInventoryModule(context.assessment);
    case "infrastructure_risk":
      return detectInfrastructureRiskModule(context);
    case "migration_questions":
      return detectMigrationQuestionsModule(context.assessment);
    case "storage_analysis":
      return detectStorageAnalysisModule(context.assessment);
    case "licensing_cost_exposure":
      return detectLicensingCostExposureModule(context.assessment);
    case "manual_assumptions":
      return detectManualAssumptionsModule(context.assessment);
    case "ai_advisory":
      return detectAiAdvisoryModule(context);
    case "report_generation":
      return detectReportGenerationModule(context.assessment);
  }
}

function buildPrimaryCta(
  modules: AssessmentCompletionModule[],
): AssessmentCompletionPrimaryCta {
  const rvtoolsModule = modules.find((module) => module.key === "rvtools_inventory");
  const reportModule = modules.find((module) => module.key === "report_generation");
  const hasMissingRecommended = modules.some(
    (module) => !module.required && RECOMMENDED_MISSING_STATUSES.has(module.status),
  );

  if (rvtoolsModule?.status !== "complete") {
    return "upload_rvtools";
  }

  if (reportModule?.status !== "complete") {
    return "generate_report";
  }

  if (hasMissingRecommended) {
    return "improve_report";
  }

  return "review_modules";
}

export function computeAssessmentCompletionSummary(
  assessment: AssessmentCompletionAssessmentInput,
): AssessmentCompletionSummary {
  const rvtoolsDetection = detectRvtoolsInventoryModule(assessment);
  const reportDetection = detectReportGenerationModule(assessment);

  const modules = assessmentCompletionModuleCatalog.map((definition) => {
    const detection =
      definition.key === "rvtools_inventory"
        ? rvtoolsDetection
        : definition.key === "report_generation"
          ? reportDetection
          : detectModule(definition, {
              assessment,
              rvtoolsStatus: rvtoolsDetection.status,
              reportStatus: reportDetection.status,
            });

    return buildCompletionModule(definition, detection);
  });

  const completionPercent = clampPercent(
    modules.reduce((total, module) => total + module.completionContribution, 0),
  );
  const reportConfidencePercent = clampPercent(
    modules.reduce((total, module) => total + module.confidenceContribution, 0),
  );
  const missingRequired = modules.filter(
    (module) => module.required && !COMPLETE_STATUSES.has(module.status),
  );
  const missingRecommended = modules.filter(
    (module) => !module.required && RECOMMENDED_MISSING_STATUSES.has(module.status),
  );
  const limitations = modules
    .filter((module) => module.limitationText && module.status !== "not_applicable")
    .map((module) => module.limitationText as string);
  const rvtoolsModule = modules.find((module) => module.key === "rvtools_inventory");

  return {
    completionPercent,
    reportConfidencePercent,
    requiredComplete: missingRequired.length === 0,
    canGenerateReport: rvtoolsModule?.status === "complete",
    modules,
    missingRequired,
    missingRecommended,
    limitations,
    primaryCta: buildPrimaryCta(modules),
  };
}
