export type Severity = "critical" | "high" | "medium" | "info";
export type EvidenceState = "Complete" | "Missing" | "Partial" | "Generated" | "Limited";
export type KeyValueRow = readonly [string, string];

export type LabScene = {
  id: string;
  number: string;
  label: string;
  title: string;
  durationMs: number;
  status: string;
  railCopy: string;
  mainCopy: string;
};

export const acmeDataset = {
  company: "ACME Corp",
  file: {
    name: "rvtools_export_acme_corp.xlsx",
    type: "VMware inventory export",
    size: "18.4 MB",
    status: "received",
  },
  inventory: [
    ["VMs", "126"],
    ["ESXi hosts", "6"],
    ["Clusters", "3"],
    ["Datastores", "14"],
    ["Port groups", "38"],
    ["VLANs", "22"],
    ["Snapshots", "19"],
    ["Possible legacy OS workloads", "5"],
  ] satisfies KeyValueRow[],
  evidence: [
    { area: "RVTools", status: "Complete" as EvidenceState },
    { area: "Backup evidence", status: "Missing" as EvidenceState },
    { area: "Application dependencies", status: "Missing" as EvidenceState },
    { area: "Proxmox target", status: "Partial" as EvidenceState },
    { area: "Network mapping", status: "Partial" as EvidenceState },
    { area: "Historical performance", status: "Missing" as EvidenceState },
  ],
  optionalEvidence: [
    ["Backup export", "Not provided"],
    ["Proxmox target export", "Partial"],
    ["Application mapping", "Not provided"],
    ["Network mapping", "Partial"],
    ["Historical performance", "Not provided"],
  ] satisfies KeyValueRow[],
  confirmed: [
    "VMware inventory received",
    "CPU / RAM allocation",
    "Storage allocation",
    "Datastores detected",
    "Snapshots detected",
    "Network objects detected",
  ],
  probable: [
    "Possible domain controllers",
    "SQL / ERP-like workloads",
    "Multi-NIC complexity",
    "Storage-heavy candidates",
    "Legacy OS candidates",
  ],
  missing: [
    "Backup evidence not provided",
    "Application dependencies unknown",
    "Historical performance missing",
    "Proxmox target partially validated",
  ],
  scores: {
    readiness: 68,
    confidence: 64,
    decision: "Conditional Go",
  },
  riskFindings: [
    { text: "Backup evidence missing", severity: "critical" as Severity },
    { text: "3 possible domain controllers", severity: "critical" as Severity },
    { text: "5 SQL / ERP-like workloads", severity: "critical" as Severity },
    { text: "7 old snapshots", severity: "high" as Severity },
    { text: "4 VMs with disks above 2 TB", severity: "high" as Severity },
    { text: "2 datastores above 85%", severity: "high" as Severity },
    { text: "9 multi-NIC VMs", severity: "medium" as Severity },
    { text: "12 outdated VMware Tools", severity: "medium" as Severity },
    { text: "6 VMs with network mapping gaps", severity: "medium" as Severity },
    { text: "14 low-risk pilot candidates detected", severity: "info" as Severity },
  ],
  vmMatrix: [
    {
      vm: "web-portal-01",
      workload: "Web App",
      complexity: "Low",
      risk: "Low",
      recommendation: "Wave 1",
    },
    {
      vm: "fileserver-02",
      workload: "File Server",
      complexity: "Medium",
      risk: "Medium",
      recommendation: "Validate storage",
    },
    {
      vm: "sql-prod-01",
      workload: "Database",
      complexity: "High",
      risk: "High",
      recommendation: "Manual review",
    },
    {
      vm: "dc-main-01",
      workload: "Domain Controller",
      complexity: "High",
      risk: "High",
      recommendation: "Special plan",
    },
    {
      vm: "erp-prod",
      workload: "ERP",
      complexity: "Critical",
      risk: "Critical",
      recommendation: "Hold",
    },
  ],
  complexitySummary: [
    "38 low-complexity candidates",
    "51 standard validation workloads",
    "22 manual review workloads",
    "15 not recommended for first wave",
  ],
  sizing: [
    ["Recommended nodes", "3-4"],
    ["RAM target", "1.8-2.5 TB"],
    ["Usable storage target", "70 TB+"],
    ["Backup capacity target", "90 TB"],
    ["HA readiness", "Conditional"],
    ["Network readiness", "Requires validation"],
  ] satisfies KeyValueRow[],
  sizingBasis: [
    "RVTools allocation data",
    "Partial Proxmox target evidence",
    "No historical performance export",
  ],
  waves: [
    {
      name: "Wave 0 - Pilot",
      detail: "3 low-risk VMs",
      note: "Validate import path, network mapping, backup / restore.",
    },
    {
      name: "Wave 1 - Low Risk",
      detail: "Web apps, test/dev, non-critical services.",
      note: "First production-like confidence step.",
    },
    {
      name: "Wave 2 - Standard Production",
      detail: "App servers, internal tools, moderate storage workloads.",
      note: "Proceed after pilot acceptance.",
    },
    {
      name: "Wave 3 - Critical Systems",
      detail: "SQL, ERP, DCs, file servers, multi-NIC systems.",
      note: "Requires dedicated planning.",
    },
    {
      name: "Hold",
      detail: "Missing backup evidence, unknown dependencies, old snapshots, storage-heavy workloads.",
      note: "Do not place in early migration waves.",
    },
    {
      name: "Retire / Rebuild",
      detail: "Legacy or non-strategic workloads.",
      note: "Avoid migrating technical debt blindly.",
    },
  ],
  vmWaveMoves: [
    "web-portal-01 -> Wave 1",
    "fileserver-02 -> Wave 2",
    "sql-prod-01 -> Wave 3 / manual review",
    "dc-main-01 -> Wave 3 / special plan",
    "erp-prod -> Hold",
  ],
  validations: [
    "Validate backup coverage and recent restore points",
    "Confirm application dependencies for critical workloads",
    "Review domain controllers under a dedicated migration plan",
    "Validate storage-heavy VMs individually",
    "Confirm Proxmox target capacity and HA assumptions",
    "Execute pilot wave before critical systems",
  ],
  reportSections: [
    ["Executive Summary", "Generated"],
    ["Evidence Received", "Generated"],
    ["Evidence Missing", "Generated"],
    ["Readiness Score", "Generated"],
    ["Confidence Score", "Generated"],
    ["VM Risk Matrix", "Generated"],
    ["Storage / Network Risks", "Generated"],
    ["Backup Evidence", "Limited"],
    ["Migration Waves", "Generated"],
    ["No-Go Items", "Generated"],
    ["Next Evidence to Collect", "Generated"],
  ] satisfies KeyValueRow[],
};

export const labScenes: LabScene[] = [
  {
    id: "standby",
    number: "00",
    label: "Standby",
    title: "Lab Opening",
    durationMs: 8000,
    status: "standby",
    railCopy: "A readiness console for VMware -> Proxmox migration planning.",
    mainCopy: "Before migrating VMware to Proxmox, know what can break.",
  },
  {
    id: "intake",
    number: "01",
    label: "Intake",
    title: "Evidence Intake",
    durationMs: 14000,
    status: "evidence received",
    railCopy: "Start with exported evidence. No agents. No production changes.",
    mainCopy: "Start with RVTools. Add more evidence when you need higher confidence.",
  },
  {
    id: "parse",
    number: "02",
    label: "Parse",
    title: "Inventory Parsing",
    durationMs: 18000,
    status: "parsing VMware inventory",
    railCopy: "The raw export is normalized into structured infrastructure evidence.",
    mainCopy: "Raw VMware exports become structured infrastructure evidence.",
  },
  {
    id: "evidence",
    number: "03",
    label: "Evidence",
    title: "Evidence Separation",
    durationMs: 20000,
    status: "validating evidence quality",
    railCopy: "Known, probable and missing evidence stay separate.",
    mainCopy: "We do not guess what the evidence does not prove.",
  },
  {
    id: "confidence",
    number: "04",
    label: "Confidence",
    title: "Evidence Confidence",
    durationMs: 16000,
    status: "calculating confidence",
    railCopy: "Confidence is reduced when critical evidence is missing.",
    mainCopy: "The system does not hide uncertainty. It measures it.",
  },
  {
    id: "risk",
    number: "05",
    label: "Risk",
    title: "Risk Engine",
    durationMs: 22000,
    status: "analyzing risk signals",
    railCopy: "Visible risks are classified by severity and migration impact.",
    mainCopy: "Risk is assembled from evidence, not invented.",
  },
  {
    id: "matrix",
    number: "06",
    label: "Matrix",
    title: "VM Complexity Matrix",
    durationMs: 20000,
    status: "classifying workloads",
    railCopy: "Each workload receives a risk level and a recommended migration action.",
    mainCopy: "Not every VM should move at the same time or under the same assumptions.",
  },
  {
    id: "scores",
    number: "07",
    label: "Scores",
    title: "Dual Score Logic",
    durationMs: 14000,
    status: "interpreting results",
    railCopy: "Readiness and confidence are not the same thing.",
    mainCopy: "A useful assessment measures both readiness and certainty.",
  },
  {
    id: "sizing",
    number: "08",
    label: "Sizing",
    title: "Target Readiness & Sizing",
    durationMs: 18000,
    status: "estimating target requirements",
    railCopy: "The destination must be validated before production workloads move.",
    mainCopy: "Infrastructure sizing is strongest when destination evidence is included.",
  },
  {
    id: "waves",
    number: "09",
    label: "Waves",
    title: "Migration Waves",
    durationMs: 21000,
    status: "generating wave plan",
    railCopy: "The plan defines what moves first, what waits and what requires review.",
    mainCopy: "A migration plan is not just about what can move. It is about what should move first.",
  },
  {
    id: "validations",
    number: "10",
    label: "Validations",
    title: "Required Validations",
    durationMs: 17000,
    status: "generating validation checklist",
    railCopy: "Missing evidence becomes action, not a hidden weakness.",
    mainCopy: "Missing evidence becomes part of the report - not a hidden weakness.",
  },
  {
    id: "report",
    number: "11",
    label: "Report",
    title: "Report Assembly",
    durationMs: 17000,
    status: "generating report",
    railCopy: "The assessment becomes an executive and technical decision pack.",
    mainCopy: "The output is not a dashboard screenshot. It is a migration decision pack.",
  },
  {
    id: "final",
    number: "12",
    label: "Decision",
    title: "Final Executive Decision",
    durationMs: 13000,
    status: "conditional decision ready",
    railCopy: "Move low-risk workloads first. Validate backup and dependencies before critical waves.",
    mainCopy: "Before migrating VMware to Proxmox, know what can break.",
  },
];

export const auditStream = [
  "Parsing vInfo...",
  "Parsing vCPU...",
  "Parsing vMemory...",
  "Parsing vDisk...",
  "Parsing vDatastore...",
  "Parsing vNetwork...",
  "Parsing vSnapshot...",
  "Parsing vTools...",
  "Normalizing inventory...",
];
